// ===== ABKÜRZUNGEN & BEGRIFFE (shared) =====
(function() {
const ABKZ={
// Allgemein / Recht
'SchKG':['SchKG','Schuldbetreibungs- und Konkursgesetz','Bundesgesetz über Schuldbetreibung und Konkurs. Regelt die zwangsweise Durchsetzung von Geldforderungen in der Schweiz.'],
'HR':['HR','Handelsregister','Öffentliches Register aller Unternehmen. Wer im HR eingetragen ist, unterliegt der Konkursbetreibung (Art. 39 SchKG).'],
'ZPO':['ZPO','Zivilprozessordnung','Regelt das Verfahren vor Zivilgerichten. Kommt bei nicht-monetären Ansprüchen zum Zug.'],
'BGE':['BGE','Bundesgerichtsentscheid','Leitentscheid des Schweizerischen Bundesgerichts. Prägt die Rechtsprechung.'],
'KoVo':['KoVo','Kostenvorschuss','Vorauszahlung an das Betreibungsamt durch den Gläubiger zur Deckung der Verfahrenskosten.'],
'RÖ':['RÖ','Rechtsöffnung','Gerichtliche Beseitigung des Rechtsvorschlags — provisorisch (bei Schuldanerkennung) oder definitiv (bei Urteil).'],
'BV':['BV','Bundesverfassung','Verfassung der Schweizerischen Eidgenossenschaft. Oberste Rechtsquelle.'],
// Arbeitsrecht
'OR':['OR','Obligationenrecht','Teil des ZGB. Art. 319–362 regeln den Einzelarbeitsvertrag.'],
'ArG':['ArG','Arbeitsgesetz','Bundesgesetz über die Arbeit. Regelt Höchstarbeitszeiten, Nacht-/Sonntagsarbeit, Jugend-/Mutterschutz.'],
'ArGV':['ArGV','Verordnung zum Arbeitsgesetz','Ausführungsbestimmungen zum ArG. ArGV 1 = allgemein, ArGV 2 = Sonderbestimmungen.'],
'L-GAV':['L-GAV','Landes-Gesamtarbeitsvertrag des Gastgewerbes','Allgemeinverbindlicher GAV für die gesamte Schweizer Gastro-/Hotelbranche. Mindeststandards für alle.'],
'GAV':['GAV','Gesamtarbeitsvertrag','Rahmenvertrag zwischen Arbeitgeber- und Arbeitnehmerverbänden mit Mindestbedingungen für eine Branche.'],
'GlG':['GlG','Gleichstellungsgesetz','Bundesgesetz über die Gleichstellung von Frau und Mann. Verbietet Diskriminierung am Arbeitsplatz.'],
'DSG':['DSG','Datenschutzgesetz','Regelt den Schutz personenbezogener Daten. AN hat Einsichtsrecht in Personalakte (Art. 25 DSG).'],
'BBG':['BBG','Berufsbildungsgesetz','Regelt die berufliche Grundbildung, Weiterbildung und Berufsberatung in der Schweiz.'],
// Personen
'AG':['AG','Arbeitgebende / Aktiengesellschaft','Im Arbeitsrecht: Arbeitgebende. Im Gesellschaftsrecht: Aktiengesellschaft.'],
'AN':['AN','Arbeitnehmende','Person, die aufgrund eines Arbeitsvertrages unselbständig erwerbstätig ist.'],
'GmbH':['GmbH','Gesellschaft mit beschränkter Haftung','Juristische Person. Bei Konkurs: wird im HR gelöscht.'],
// Zeitbegriffe
'DJ':['DJ','Dienstjahr(e)','Dauer des Arbeitsverhältnisses. Bestimmt Kündigungsfristen und Sperrfristen.'],
'ML':['ML','Monatslohn / Monatslöhne','Brutto-Monatslohn. Basis für Berechnungen wie 13. ML, Entschädigungen.'],
'KT':['KT','Kalendertage','Alle Tage inkl. Wochenende/Feiertage. Ferien: 35 KT = 5 Wochen.'],
// Arbeitszeit
'AZ':['AZ','Arbeitszeit','Vertragliche oder gesetzliche Arbeitszeit. L-GAV: 42h/Woche.'],
'ÜSt':['ÜSt','Überstunden','Arbeit über die vertragliche Arbeitszeit (z.B. über 42h). Kompensation: 100% oder 125%.'],
// Versicherungen
'AHV':['AHV','Alters- und Hinterlassenenversicherung','1. Säule der Altersvorsorge. Obligatorisch für alle in der Schweiz Erwerbstätigen.'],
'IV':['IV','Invalidenversicherung','Versicherung bei dauerhafter Erwerbsunfähigkeit. 1. Säule.'],
'ALV':['ALV','Arbeitslosenversicherung','Versicherung bei Stellenverlust. Pflichtbeitrag für alle AN.'],
'BVG':['BVG','Berufliche Vorsorge','2. Säule (Pensionskasse). Pflicht ab CHF 22\'050 Jahreslohn.'],
'UVG':['UVG','Unfallversicherungsgesetz','Obligatorische Unfallversicherung für alle AN. BU: AG zahlt. NBU: AN ab 8h/Woche.'],
'EO':['EO','Erwerbsersatzordnung','Lohnersatz bei Militärdienst, Zivildienst, Mutterschaft.'],
'BU':['BU','Berufsunfall','Unfall bei oder wegen der Arbeit. Versichert über UVG, Prämie zahlt AG.'],
'NBU':['NBU','Nichtberufsunfall','Unfall ausserhalb der Arbeit. Prämie zahlt AN (ab 8h/Woche versichert).'],
'SCA':['SCA','Swiss Catering Association','Arbeitgeberverband im Gastgewerbe, Teil der L-GAV-Vertragsparteien.'],
'EAV':['EAV','Einzelarbeitsvertrag','Art. 319ff. OR. Vertrag zwischen einzelnem AG und AN über persönliche Arbeitsleistung gegen Lohn.'],
'AVIG':['AVIG','Arbeitslosenversicherungsgesetz','Regelt die Arbeitslosenversicherung und die Insolvenzentschädigung (Art. 51ff.).'],
'SECO':['SECO','Staatssekretariat für Wirtschaft','Bundesbehörde für Wirtschaftspolitik, Arbeit und Arbeitsmarkt.'],
'EFZ':['EFZ','Eidgenössisches Fähigkeitszeugnis','Abschluss einer 3- oder 4-jährigen beruflichen Grundbildung (Lehre).'],
'TGV':['TGV','Taggeldversicherung','Versicherung für Lohnersatz bei Krankheit. Im Gastgewerbe Pflicht: 720 Tage, 80%.'],
'Jahresbetrieb':['Jahresbetrieb','Ganzjährig geöffneter Gastgewerbebetrieb','42h/Woche. Einsatzplan: 2 Wochen im Voraus für 2 Wochen. Ruhetagekompensation innert 4 Wochen.'],
'Saisonbetrieb':['Saisonbetrieb','Saisonal geöffneter Gastgewerbebetrieb','43,5h/Woche. Einsatzplan: 1 Woche im Voraus für 1 Woche. Ruhetagekompensation innert 12 Wochen. Während Saison grundsätzlich nicht kündbar.'],
'Kleinbetrieb':['Kleinbetrieb','Betrieb mit max. 4 Mitarbeitenden','45h/Woche. Max. 4 MA (inkl. Familie) mit total 400 Stellenprozenten. Dazu max. 3 Aushilfen unter CHF 2500/Jahr.'],
'Saisonvertrag':['Saisonvertrag','Befristeter Vertrag für eine Saison','Endet ohne Kündigung. Während Saison grundsätzlich nicht kündbar (Art. 6 Abs. 3 L-GAV). Kündbarkeit muss schriftlich vereinbart werden.'],
'Subordination':['Subordination','Weisungsgebundenheit','AN steht im Dienstverhältnis und muss Anweisungen des AG befolgen. Zentrales Merkmal des Arbeitsvertrags — unterscheidet ihn von Werkvertrag und Auftrag.'],
'Dauerschuldverhältnis':['Dauerschuldverhältnis','Vertrag mit sich wiederholenden Leistungen','Arbeit gegen Lohn, fortlaufend. Gegenstück: Zielschuldverhältnis (einmalige Leistung, z.B. Werkvertrag).'],
'Mankohaftung':['Mankohaftung','Kollektive Haftung für Fehlbeträge','Im Gastgewerbe NICHTIG — Betriebsrisiko liegt beim AG. Haftung nur bei bekanntem, individuellem Verursacher (Art. 321e OR).'],
'Günstigkeitsprinzip':['Günstigkeitsprinzip','GAV-Normen nur zugunsten AN änderbar','Vertragliche Abmachungen die schlechter als GAV = nichtig. Bessere Bedingungen = immer erlaubt.'],
'Coupure':['Coupure','Geteilter Dienst','Arbeitstag mit Unterbruch (z.B. 10–14 Uhr, dann 18–22 Uhr). Für Jugendliche unter 18 grundsätzlich verboten.'],
'Probezeit':['Probezeit','Gegenseitige Kennenlernphase','L-GAV: 14 Kalendertage (max. 3 Monate verlängerbar). Kündigung: 3 Tage. Kein zeitlicher Kündigungsschutz (Art. 336c gilt nicht).'],
'Sperrfrist':['Sperrfrist','Zeitraum mit Kündigungsverbot für AG','Kündigung während Sperrfrist = nichtig. Vor Sperrfrist = Frist ruht. Krankheit: 30/90/180 Tage. Schwangerschaft: ganze Zeit + 16 Wochen.'],
'Nachtarbeit':['Nachtarbeit','Arbeit zwischen 23 und 6 Uhr','Im Gastgewerbe ohne Bewilligung erlaubt. Vorübergehend: 25% Lohnzuschlag. Dauernd (>25 Nächte): 10% Zeitzuschlag + Arztuntersuchung.'],
'Existenzminimum':['Existenzminimum','Unpfändbarer Minimalbetrag','Grundbedarf + Miete + Krankenkasse. Individuell berechnet. Lohn darf nie unter Existenzminimum verrechnet werden (Art. 323b Abs. 2 OR).'],
'Freistellung':['Freistellung','Ordentliche Kündigung ohne Arbeitspflicht','AG verzichtet auf Arbeitsleistung. Sperrfristen verlängern trotzdem! 1/3 der Zeit kann als Ferien gelten, Rest für Stellensuche.'],
// === CONTROLLING 2 ===
'KPI':['KPI','Key Performance Indicator — Steuerungsgrösse','Mithilfe von KPIs werden strategische Ziele operationalisiert (messbar gemacht). Sie dienen als Entscheidungshilfe und richten den Fokus auf wesentliche Entwicklungen.'],
'ROI':['ROI','Return on Investment — Gesamtkapitalrentabilität','Zentrale finanzwirtschaftliche Zielgrösse. Im DuPont-Schema: ROI = Umsatzrentabilität × Kapitalumschlag. Misst die Fähigkeit des Managements zur wirtschaftlich optimalen Nutzung des investierten Vermögens.'],
'RoE':['RoE','Return on Equity — Eigenkapitalrendite','= Reingewinn ÷ Ø Eigenkapital × 100%. Zeigt, wie sich das von den Eigenkapitalgebern zur Verfügung gestellte Kapital verzinst hat.'],
'RoA':['RoA','Return on Assets — Gesamtkapitalrendite','= Reingewinn ÷ Ø Gesamtkapital × 100%. Misst die gesamten Rückflüsse an die Kapitalgeber, losgelöst von der konkreten Finanzierungsform.'],
'EBIT':['EBIT','Earnings before Interest and Taxes','= Jahresergebnis + direkte Steuern ± Finanzaufwand/-ertrag. Zeigt das operative Ergebnis vor Zinsen und Steuern. Wichtig für Peer-Vergleiche.'],
'EBITDA':['EBITDA','Earnings before Interest, Taxes, Depreciation & Amortisation','= EBIT + Abschreibungen auf Sachanlagen + Amortisationen auf immaterielle Anlagen. Zeigt die operative Ertragskraft eines Unternehmens — ob überhaupt eine funktionierende Geschäftstätigkeit vorhanden ist.'],
'EBT':['EBT','Earnings before Taxes','= Jahresergebnis + direkte Steuern. Zeigt das Ergebnis vor Steuern. Ein Unternehmen mit positivem EBITDA kann trotzdem einen negativen EBT aufweisen (z.B. durch hohe Abschreibungen).'],
'NPV':['NPV','Net Present Value — Kapitalwert','= Summe aller diskontierten Cashflows − Investitionssumme. NPV > 0 = Projekt generiert Mehrwert → investieren. Basiert auf dem Discounted-Cash-Flow-Ansatz (DCF).'],
'WACC':['WACC','Weighted Average Cost of Capital','= (FK-Kosten% × FK/GK) + (EK-Kosten% × EK/GK). Gewogener Durchschnitt der Kapitalkosten. Wird als kalkulatorischer Zinsfuss für Investitionsrechnungen verwendet.'],
'FIBU':['FIBU','Finanzbuchhaltung (externes Rechnungswesen)','Obligatorisch, gesetzlich geregelt (OR 957ff.), vergangenheitsorientiert. Liefert Bilanz, Erfolgsrechnung, Geldflussrechnung und Anhang. Richtet sich an externe Empfänger (Aktionäre, Banken, Steuerbehörde).'],
'BEBU':['BEBU','Betriebsbuchhaltung (internes Rechnungswesen)','Freiwillig, zukunftsorientiert, flexibel. Dient der Steuerung durch zuverlässige innerbetriebliche Informationen. Ermöglicht Soll-Ist-Vergleich. Umfasst Kostenrechnung, Investitionsrechnung, Budgetierung.'],
'BSC':['BSC','Balanced Scorecard','Ausgewogenes Kennzahlensystem von Kaplan & Norton (1992). 4 Perspektiven: Finanziell, Kunden, Interne Prozesse, Lernen & Entwicklung. Alle Kennzahlen müssen Strategiebezug haben und durch Ursache-Wirkungs-Ketten verbunden sein.'],
'CCC':['CCC','Cash Conversion Cycle — Kapitalbindungsdauer','= DIO + DSO − DPO. Gibt an, wie viele Tage Kapital gebunden ist vom Einkauf bis zum Zahlungseingang der Kunden. Je kürzer, desto besser für die Liquidität.'],
'DSO':['DSO','Days Sales Outstanding — Debitorenfrist','= Ø Forderungen LuL ÷ Betriebsertrag × 360 Tage. Wie lange wartet das Unternehmen auf sein Geld? Verbesserung durch optimiertes Mahnwesen und kürzere Zahlungsfristen.'],
'DIO':['DIO','Days Inventory Outstanding — Lagerdauer','= Ø Warenvorräte ÷ Warenaufwand × 360 Tage. Wie lange liegen Waren im Lager? Nicht nur minimieren — Lieferfähigkeit muss erhalten bleiben!'],
'DPO':['DPO','Days Payable Outstanding — Kreditorenfrist','= Ø Verbindlichkeiten LuL ÷ Warenaufwand × 360 Tage. Wie lange dauert die Bezahlung an Lieferanten? Hoher Wert = geringere Kapitalbindung.'],
'DDR':['DDR','Doppelte Deckungsbeitragsrechnung','DDR-Wert = DB in CHF × 2 + DB-Marge% ÷ 2. Index für Wirtschaftlichkeit verschiedener Produkte. Hoher DDR-Wert = aktiv verkaufen! Kombiniert mit Sales-Mix für optimale Angebotsgestaltung.'],
'DB':['DB','Deckungsbeitrag','= Nettoverkaufspreis − variable Kosten pro Stück. Betrag, der zur Deckung der Fixkosten und zur Erzielung eines Gewinns verbleibt. Kann in CHF oder % (DB-Marge) angegeben werden.'],
'APM':['APM','Alternative Performance Measures','EB-Ziffern (EBT, EBIT, EBITDA) die keinen Regulierungen unterliegen. Vergleichbarkeit kann durch unterschiedliche Bewertungsmethoden und Sondereffekte erschwert werden.'],
'MWST':['MWST','Mehrwertsteuer','Indirekte Steuer auf Konsum. CH seit 1.1.2024: Normalsatz 8.1% (Restaurant), Sondersatz 3.8% (Beherbergung inkl. Frühstück), reduzierter Satz 2.6% (Take-away). Durchlaufender Posten — kein Einfluss auf Gewinn.'],
'RevPAR':['RevPAR','Revenue Per Available Room','= Rooms Revenue ÷ (Zimmeranzahl × Betriebstage). Wichtigste Metrik der Hotellerie. Schliesst die Lücke zwischen OCC% und ADR. Indikator für Profitabilität und Wirksamkeit von Preisstrategien.'],
'ADR':['ADR','Average Daily Rate — Durchschnittliche Tagesrate','= Rooms Revenue ÷ Anzahl verkaufte Zimmer. Bezieht sich auf den Durchschnittspreis aller verkauften Zimmer. ADR ≠ RevPAR: ADR = nur verkaufte, RevPAR = alle verfügbaren Zimmer.'],
'GOI':['GOI','Gross Operating Income — Bruttobetriebserfolg','= Betriebsertrag − direkter Aufwand (Warenkosten + direkte Personalkosten). Erste Stufe der Erfolgsanalyse im Hotel-Controlling.'],
'GOP':['GOP','Gross Operating Profit — Bruttobetriebsergebnis','= GOI − indirekter Betriebsaufwand (Verwaltung, Marketing, Unterhalt etc.). Zeigt die operative Ertragskraft des Betriebs vor Liegenschaftskosten und Abschreibungen.'],
'DCF':['DCF','Discounted Cash Flow','Methode zur Bewertung von Investitionen und Unternehmen. Zukünftige Cashflows werden mit einem Kapitalkostensatz (WACC) auf den heutigen Wert diskontiert. Grundlage für NPV-Berechnung.'],
'Kostenträger':['Kostenträger','Kalkulationsobjekt in der Kostenrechnung','Produkte, Menüs, Profitcenter etc. Die durch den Verkauf erzielten Erlöse müssen die verursachten Kosten «tragen». Kostenträgerrechnung = wofür sind Kosten angefallen?'],
'Kostenstelle':['Kostenstelle','Organisatorische Einheit für Kostenzuordnung','Ort der Kostenentstehung. Bsp: Rooms Division, F&B, Wellness, Administration. Hauptkostenstellen → direkt auf Kostenträger. Hilfskostenstellen → zuerst auf Hauptkostenstellen verteilt.'],
'Kostenspaltung':['Kostenspaltung','Aufteilung in fixe und variable Kosten','Voraussetzung für die Teilkostenrechnung. K(x) = K_var × x + K_fix. Fixe Kosten = unabhängig von Auslastung. Variable Kosten = steigen/sinken proportional mit Absatz.'],
'Selbstkosten':['Selbstkosten','Total aller Kosten eines Produktes','= Herstellkosten + Verwaltungs- und Vertriebskosten. Ab den Selbstkosten beginnt man Gewinn zu erwirtschaften. Basis für die Preisbestimmung.'],
'Herstellkosten':['Herstellkosten','Kosten des gesamten Produktionsprozesses','= Einzelkosten (Material + Fertigung) + Gemeinkosten (Produktion). Noch ohne Verwaltung und Vertrieb.'],
'Nutzschwelle':['Nutzschwelle','Break-even-Point — Gewinnschwelle','Punkt, an dem Erlöse = Totalkosten (Gewinn = 0). Mengenmässig: Fixkosten ÷ DB pro Stück. Wertmässig: Fixkosten ÷ DB-Marge%. Unterhalb = Verlust, oberhalb = Gewinn.'],
'Cashflow':['Cashflow','Geldfluss aus Betriebstätigkeit','= Einnahmen − liquiditätswirksame Betriebskosten. Oder indirekt: Reingewinn + Abschreibungen + kalk. Zinsen. Zeigt den Liquiditätszufluss aus der Investitionstätigkeit.'],
'Liquidationserlös':['Liquidationserlös','Netto-Mittelzufluss am Ende der Nutzungsdauer','= Verkaufserlös − Entsorgungs-/Demontagekosten. Statisch: vermindert Abschreibung, erhöht Durchschnittskapital. Dynamisch: zusätzliche Einnahme am Ende.'],
// === FINANCIAL ACCOUNTING 3 ===
'GoB':['GoB','Grundsätze ordnungsmässiger Buchführung','OR 957a Abs. 2: Vollständigkeit & Wahrheit, Belegnachweis, Klarheit & Nachprüfbarkeit. Regeln das Erfassen der Geschäftsfälle während der Rechnungsperiode.'],
'GoR':['GoR','Grundsätze ordnungsmässiger Rechnungslegung','OR 958c Abs. 1: Klarheit, Vollständigkeit, Wahrheit, Wesentlichkeit, Vorsicht, Stetigkeit, Verrechnungsverbot. Bilden die Grundlage für den Geschäftsbericht.'],
'SKHG':['SKHG','Schweizer Kontenrahmen Hotellerie & Gastronomie','Branchenspezifischer Kontenrahmen für Hotels und Restaurants. Basiert auf dem Kontenrahmen KMU, ist aber detaillierter und auf die Bedürfnisse der Branche zugeschnitten.'],
'ESTV':['ESTV','Eidgenössische Steuerverwaltung','Bundesbehörde für Steuern. Zuständig u.a. für die Mehrwertsteuer, Verrechnungssteuer und direkte Bundessteuer.'],
'FLL':['FLL','Forderungen aus Lieferungen und Leistungen','Aktivkonto (Konto 1100). Offene Kundenrechnungen — Geld das uns noch geschuldet wird.'],
'VLL':['VLL','Verbindlichkeiten aus Lieferungen und Leistungen','Passivkonto (Konto 2000). Offene Lieferantenrechnungen — Geld das wir noch schulden.'],
'ARA':['ARA','Aktive Rechnungsabgrenzung','Aktivkonto im UV. Vorausbezahlter Aufwand oder noch nicht erhaltener Ertrag. Buchung Ende Periode: ARA / Aufwandkonto.'],
'PRA':['PRA','Passive Rechnungsabgrenzung','Passivkonto im kfr. FK. Noch nicht bezahlter Aufwand oder voraus erhaltener Ertrag. Buchung Ende Periode: Aufwandkonto / PRA.'],
'ERP':['ERP','Enterprise Resource Planning','Softwarelösung zur ganzheitlichen Steuerung aller Unternehmensprozesse. Umfasst FiBu, Lohn, Lager, CRM etc. In der Hotellerie: Mirus hat >80% Marktanteil.'],
'KER':['KER','Kurzfristige Erfolgsrechnung','Unterjährige Erfolgsrechnung (monatlich/quartalsweise) zur laufenden Erfolgskontrolle. Basis für Rechnungsabgrenzungen.'],
// === OPERATIVES MARKETING ===
'CRM':['CRM','Customer Relationship Management','Strategie zum systematischen Aufbau und zur Pflege von Kundenbeziehungen. Ziele: Loyalität fördern, durch Empfehlungen Neukunden gewinnen, beste Kund:innen identifizieren und langfristig binden. CRM-Systeme bieten eine 360-Grad-Sicht auf Gäste (Kontakte, E-Mail-Automation, Guest History). Wichtig: CRM ≠ PMS!'],
'PMS':['PMS','Property Management System','Operatives System für den Hotelbetrieb: Check-in/out, Zimmerbelegung, Rechnungen, Reservierungen. Fokus auf Abwicklung des täglichen Betriebs. Wird von Rezeption, Housekeeping und Management genutzt. Ergänzt sich mit CRM, ist aber NICHT dasselbe.'],
'USP':['USP','Unique Selling Proposition — Alleinstellungsmerkmal','Klarer, differenzierender Vorteil gegenüber Wettbewerbern. Kann auf allen 3 Ebenen des Leistungsmix liegen: Kernprodukt, formales Produkt oder erweitertes Produkt. Beantwortet die Frage: Warum soll der Gast genau zu UNS kommen?'],
'UCP':['UCP','Unique Communication Proposition','Einzigartigkeit durch gezielte werbliche bzw. kommunikative Alleinstellung. Ergänzt den USP auf der kommunikativen Ebene — wie das Unternehmen seine Einzigartigkeit vermittelt.'],
'CXM':['CXM','Customer Experience Management','Geplante und gezielte Gestaltung aller direkten und indirekten Kontaktpunkte (Touchpoints) mit dem Ziel, ein einheitliches, positives Markenerlebnis zu schaffen. Phasen: vor, während und nach dem Aufenthalt. Erlebnis schlägt Rabatt!'],
'CI':['CI','Corporate Identity — Unternehmensidentität','Soll nach aussen wie nach innen ein einheitliches und glaubhaftes Bild (Image) erzeugen. Besteht aus 3 Elementen: Corporate Design (CD), Corporate Communication (CC) und Corporate Behaviour (CB). Alle 3 müssen zusammenpassen — sonst Misstrauen!'],
'SWOT':['SWOT','Strengths, Weaknesses, Opportunities, Threats','Zentrales Analyse-Tool im Marketing. Verbindet interne Analyse (Stärken/Schwächen = beeinflussbar) mit externer Analyse (Chancen/Gefahren = nicht kontrollierbar). Aussagen müssen auf belegbaren Quellen basieren. Das Fazit ist der wichtigste Teil!'],
'AIDA':['AIDA','Attention, Interest, Desire, Action','Wirkungsstufenmodell der Kommunikation. Zeigt die 4 Phasen zur Kaufentscheidung: 1. Aufmerksamkeit wecken, 2. Interesse wecken, 3. Wunsch auslösen, 4. Handlung auslösen. Oft braucht es verschiedene Massnahmen pro Stufe!'],
'OTA':['OTA','Online Travel Agency','Online-Reisebüro wie Booking.com, Expedia, Hotels.com. Indirekte Distribution mit 15–25% Kommissionen. Bieten weltweite Reichweite, aber hohe Kosten und Kontrollverlust. Ziel: Direktbuchungsanteil maximieren!'],
'SEO':['SEO','Search Engine Optimization — Suchmaschinenoptimierung','Massnahmen zur Verbesserung der organischen (unbezahlten) Suchergebnisse. On-page: Keywords (3–5%), min. 300 Wörter/Seite, Alt-Texte, sprechende URLs. SEO ist ein NIE abgeschlossener Prozess! Neu: KI-Einfluss durch Google SGE.'],
'SEA':['SEA','Search Engine Advertising — Suchmaschinenwerbung','Bezahlte Anzeigen in Suchmaschinen (z.B. Google Ads). Kosten: CPC (Cost per Click) — man zahlt nur wenn jemand klickt. KI-Features: Smart Bidding, Responsive Ads, Performance Max.'],
'SEM':['SEM','Search Engine Marketing — Suchmaschinenmarketing','Oberbegriff für alle Massnahmen im Suchmaschinen-Bereich. SEM = SEO (organisch) + SEA (bezahlt). Ziel: Sichtbarkeit in Suchmaschinen erhöhen.'],
'CPC':['CPC','Cost per Click','Kosten pro Klick bei Online-Werbung (z.B. Google Ads). Man zahlt nur, wenn ein Nutzer tatsächlich auf die Anzeige klickt. Ermöglicht genaue Budgetkontrolle und Erfolgsmessung.'],
'CTR':['CTR','Click-Through-Rate — Klickrate','Verhältnis von Klicks zu Impressionen in Prozent. CTR = Klicks ÷ Impressionen × 100. Wichtige Kennzahl für die Effektivität von Online-Werbung und E-Mail-Marketing.'],
'TKP':['TKP','Tausend-Kontakt-Preis','Kosten, um 1000 Personen der Zielgruppe mit einer Werbemassnahme zu erreichen. Ermöglicht den Vergleich verschiedener Medien (Intermedia-Vergleich: Print vs. Online) und innerhalb einer Gattung (Intramedia-Vergleich).'],
'CPM':['CPM','Cost per Mille','Englische Bezeichnung für den Tausend-Kontakt-Preis (TKP). Kosten pro 1000 Impressionen einer Online-Werbeanzeige. Standard-Abrechnungsmodell für Display-Werbung.'],
'DOSM':['DOSM','Director of Sales & Marketing','Führungsverantwortung im Hotel-Marketing. Zuständig für die gesamte Marketing- und Vertriebsstrategie sowie das Budget. Leitet DOM (Marketing) und DOS (Sales).'],
'DOM':['DOM','Director of Marketing','Verantwortlich für die operative Umsetzung der Marketingstrategie. Führt das Marketingteam (Marketing Manager, Digital Marketing Manager). Rapportiert an DOSM.'],
'DOS':['DOS','Director of Sales','Verantwortlich für die Vertriebsstrategie und internationale Partnerschaften. Führt die Sales Manager. Fokus auf Akquise, B2B-Geschäft und Vertriebskanäle.'],
'DSGVO':['DSGVO','Datenschutz-Grundverordnung','EU-weites Datenschutzrecht. Regelt die Verarbeitung personenbezogener Daten. Kern: Einwilligung (Opt-in), Zweckbindung, Recht auf Löschung, Datenminimierung. In der Schweiz gilt das revidierte DSG (revDSG) mit ähnlichen Grundsätzen.'],
'GDS':['GDS','Global Distribution System','Globale Buchungssysteme wie Amadeus, Sabre, Travelport. Verbinden Hotels mit Reisebüros und OTAs weltweit. Indirekte Distribution mit Kommissionen.'],
'Conversion Rate':['Conversion Rate','Umwandlungsrate','Prozentsatz der Website-Besucher, die eine gewünschte Aktion ausführen (z.B. Buchung, Newsletter-Anmeldung). Hotels: ca. 2% — d.h. 98 von 100 Besuchern buchen NICHT. Jede Verbesserung wirkt direkt auf den Umsatz.'],
'Double-Opt-in':['Double-Opt-in','Zweistufige Einwilligung','Standard für Newsletter-Anmeldungen: 1. Nutzer gibt E-Mail ein, 2. Bestätigungs-E-Mail mit Link → erst nach Klick ist Anmeldung gültig. Pflicht gemäss DSGVO/revDSG. Schützt vor Missbrauch.'],
'Omnichannel':['Omnichannel','Kanalübergreifende Vernetzung','Alle Kommunikations- und Vertriebskanäle sind vernetzt und bieten ein einheitliches Erlebnis. Reibungsloser Wechsel zwischen online und offline. ≠ Multichannel (Kanäle nebeneinander, evtl. widersprüchlich).'],
'Franchise':['Franchise','Lizenzbasiertes Betriebskonzept','Kooperationsform mit höchster Bindungsintensität. Franchise-Nehmer übernimmt Betriebskonzept und betreibt es nach den Spielregeln des Gebers. Beispiele: McDonalds, Starbucks. Vorteile Geber: Expansion ohne Kapital. Vorteile Nehmer: Know-how, geringeres Risiko.'],
'Preiselastizität':['Preiselastizität','Reaktion der Nachfrage auf Preisänderungen','Elastisch: Nachfrage reagiert stark (z.B. Hotel im November — viel Angebot). Unelastisch: Nachfrage bleibt gleich (z.B. Silvester — Gäste können nicht ausweichen). Wichtig für Yield Management und Preisdifferenzierung.'],
'Preisbündelung':['Preisbündelung','Produkte als Paket verkaufen','Mehrere Leistungen als Paket zu einem Vorteilspreis. Reine Bündelung (nur als Paket) oder gemischte Bündelung (auch einzeln erhältlich). Ziel: Auslastung optimieren, wenig genutzte Leistungen fördern, Kundschaft ans «One Stop Shopping» binden.'],
'Decoy-Effekt':['Decoy-Effekt','Köder-Effekt in der Preispsychologie','Eine dritte Option wird eingeführt, die eine der anderen attraktiver macht. Beispiel: Standard CHF 189, Komfort CHF 259, Deluxe CHF 289 → Komfort ist der «Köder» → meiste wählen Deluxe, weil nur CHF 30 mehr.'],
'Anker-Effekt':['Anker-Effekt','Psychologische Preisverankerung','Der zuerst wahrgenommene Preis «verankert» sich im Kopf und beeinflusst die Beurteilung aller folgenden Preise. Taktik: Zuerst die teure Suite zeigen, dann das Standardzimmer → wirkt im Vergleich günstig.'],
'Marketing-Mix':['Marketing-Mix','Kombination der Marketinginstrumente','Die optimale Kombination aller Marketinginstrumente zur Zielerreichung. Klassisch: 4 Ps (Product, Price, Place, Promotion). Erweitert für Dienstleistungen: 7 Ps (+ People, Process, Physical Evidence). Alle Ps müssen aufeinander abgestimmt sein (integriertes Marketing).'],
'Marktsegmentierung':['Marktsegmentierung','Aufteilung des Gesamtmarktes in Zielgruppen','Gesamtmarkt in homogene Kaufgruppen aufteilen. Kriterien: demografisch (Alter, Einkommen), geografisch (Region), psychografisch (Lebensstil, Werte), verhaltensbezogen (Kaufmotive, Markentreue). Je genauer die Segmente, desto gezielter die Ansprache.'],
'Positionierung':['Positionierung','Strategische Markenabgrenzung','Oberziel der Kommunikation: Wie hebt sich die Marke in den Köpfen der Kund:innen von der Konkurrenz ab? Anforderungen: relevant, konzentriert, klar abgegrenzt, zukunftsorientiert, flexibel, operationalisierbar. Darstellung: Positionierungskreuz.'],
// === HRM 2 ===
'HRM':['HRM','Human Resources Management','Strategische Personalfunktion: umfasst Planung, Gewinnung, Betreuung, Honorierung, Entwicklung und Trennung. HR-Leitung sollte Mitglied der Geschäftsleitung sein.'],
'BGM':['BGM','Betriebliches Gesundheitsmanagement','Zentraler Punkt in der modernen Personalarbeit. Open-Door-Politik und geschulte Führungskräfte sind essenziell — gerade in der Hotellerie mit Fachkräftemangel.'],
'MbO':['MbO','Management by Objectives','Führen durch Zielvereinbarungen. Vorgesetzte und MA vereinbaren gemeinsam messbare Ziele. Wird in der Personalentwicklung und bei Qualifikationsgesprächen eingesetzt.'],
'PeNeKo':['PeNeKo','Personalnebenkosten','Indirekte Personalkosten: freiwillige Sozialbeiträge, Entgeltfortzahlung, Urlaubsgeld, Weihnachtsgeld, Aus- und Weiterbildungskosten. Kommen zu den direkten Personalkosten hinzu.'],
'Assessment-Center':['Assessment-Center','Praxissimulationsverfahren zur Personalauswahl','Kombination von Tests, Interviews und Gruppenarbeiten zur umfassenden Beurteilung von Kandidaten. Sehr gründlich aber kostspielig. Zählt zu den T-Daten.'],
'STAR':['STAR','Situation, Task, Action, Result','Verhaltensorientierte Interviewmethode aus den USA. Kandidaten schildern eine konkrete Situation, die Aufgabe, ihr Handeln und das Ergebnis. Variante des Verhaltensdreiecks.'],
// === SALES ===
'RFP':['RFP','Request for Proposal','Elektronische Ausschreibung für Hotelverträge. Grosse Unternehmen nutzen Tools wie Lanyon oder Nexus. Beginnt oft Mitte des Kalenderjahres für das Folgejahr. Exakte Einhaltung nötig — Abweichungen = Vertragsverlust.'],
'TMC':['TMC','Travel Management Company','Spezialisiertes Firmenreisebüro, das Geschäftsreisen organisiert. Beispiele: Amex GBT, BCD Travel, CWT. Wird oft von Grossunternehmen beauftragt.'],
'LRA':['LRA','Last Room Availability','Garantie, dass das letzte verfügbare Zimmer zum vereinbarten Firmenpreis (Corporate Rate) verkauft wird. Wichtige Vertragsklausel bei Corporate-Ratenverhandlungen.'],
'FAB':['FAB','Feature – Advantage – Benefit','Nutzenargumentation im Verkauf: Merkmal (sachliche Produkteigenschaft) → Vorteil (allgemeiner Nutzen) → Nutzen (individueller Kundennutzen). Immer nur eine Kette pro Argumentation. Zentral: «Es wird nie das Produkt gekauft — es wird immer der Nutzen erworben.»'],
'SMERF':['SMERF','Social, Military, Education, Religious, Fraternal','Bezeichnung für Freizeitreisegruppen. Werden vom Veranstalter oft als Serie eingekauft. Gleiche Prozesse wie Paketreisen für Individuelle.'],
'Robinsonliste':['Robinsonliste','Sperrliste gegen unerwünschte Werbung','Privatpersonen auf der Robinsonliste dürfen nicht mit Telemarketing kontaktiert werden. Im aktiven Telefonverkauf unbedingt prüfen!'],
'Kinesik':['Kinesik','Wissenschaft der Körpersprache','Nichtsprachlicher (nonverbaler) Teil der Kommunikation. Kann schwer «lügen», da viele Aspekte unbewusst ablaufen. Umfasst Gestik, Mimik, Körperhaltung, Blickkontakt, räumliches Verhalten.'],
};
window.TIS = window.TIS || {};
window.TIS.abkz = ABKZ;
})();
