// ===== KURS: SALES =====
// Auto-generated module for This Is Student
(function() {

const courseConfig = {
  id: 'sales',
  name: 'Sales',
  pages: ['sales','sales_kap1','sales_kap2','sales_kap3','sales_mind','sales_kart','sales_quiz','sales_glossar'],
  subNav: [
    {s:'sales',l:'Übersicht'},
    {s:'sales_kap1',l:'1 Einordnung'},
    {s:'sales_kap2',l:'2 Verkaufsgespräche'},
    {s:'sales_kap3',l:'3 Verkaufsplanung'},
    {s:'sales_mind',l:'Zusammenfassung'},
    {s:'sales_kart',l:'Karten'},
    {s:'sales_quiz',l:'Quiz'},
    {s:'sales_glossar',l:'Glossar'}
  ],
  navButton: '<button class="nl nl-main" data-s="sales" onclick="go(\'sales\')" style="display:none">Sales</button>'
};

const courseHTML = `

<!-- SALES HOME -->
<div class="sec" id="sales">
<div style="border-radius:24px;padding:36px 32px;margin-bottom:32px;background:linear-gradient(135deg,rgba(56,182,232,.06),rgba(175,82,222,.04));border:1px solid var(--bd);position:relative;overflow:hidden">
<div style="position:absolute;top:-40px;right:-40px;width:160px;height:160px;border-radius:50%;background:linear-gradient(135deg,rgba(56,182,232,.1),rgba(175,82,222,.08))"></div>
<div style="position:relative;z-index:1">
<div style="font-size:12px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:var(--ac);margin-bottom:8px">Semester 5 · Betriebswirtschaft</div>
<h1 style="font-size:32px;letter-spacing:-.6px;margin-bottom:8px">Sales</h1>
<p style="font-size:15px;color:var(--tx2);margin-bottom:0">Dozent: Christian Gottstein · SHL Schweizerische Hotelfachschule Luzern</p>
</div></div>
<div class="hl">Durchgängiges Fallbeispiel: <strong>Hotel &amp; Restaurant «Bellevue»</strong> — 4-Sterne-Superior in Luzern, 120 Zimmer, zwei Restaurants, Wellnessbereich, 5 Tagungsräume. Familie Meier, 3. Generation. Sales-Team: Lisa Meier (DOS), Marc Brunner (Corporate &amp; MICE), Sophie Keller (Leisure &amp; Events).</div>
<div style="font-size:13px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:var(--tx3);margin-bottom:14px">Theorie · 3 Kapitel</div>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px;margin-bottom:36px">
<div class="c ck" onclick="go('sales_kap1')" style="padding:20px 22px;display:flex;gap:14px;align-items:flex-start"><div style="width:32px;height:32px;border-radius:10px;background:var(--al);color:var(--ac);display:flex;align-items:center;justify-content:center;font-weight:700;font-size:14px;flex-shrink:0">1</div><div><div class="ct2">Einordnung Verkauf</div><div class="cd">Marketing-Mix, Vertrieb, Segmente, Einkaufsprozesse, Kundentypen</div></div></div>
<div class="c ck" onclick="go('sales_kap2')" style="padding:20px 22px;display:flex;gap:14px;align-items:flex-start"><div style="width:32px;height:32px;border-radius:10px;background:var(--gl);color:var(--g);display:flex;align-items:center;justify-content:center;font-weight:700;font-size:14px;flex-shrink:0">2</div><div><div class="ct2">Verkaufsgespräche</div><div class="cd">Kommunikation, Fragetechniken, 7 Phasen, FAB, Preisnennung, Einwände</div></div></div>
<div class="c ck" onclick="go('sales_kap3')" style="padding:20px 22px;display:flex;gap:14px;align-items:flex-start"><div style="width:32px;height:32px;border-radius:10px;background:var(--pl);color:var(--pr);display:flex;align-items:center;justify-content:center;font-weight:700;font-size:14px;flex-shrink:0">3</div><div><div class="ct2">Verkaufsplanung</div><div class="cd">Massnahmen, Analyse, ABC, Pareto, 6W-Ziele, Budget</div></div></div></div>
<div style="font-size:13px;font-weight:600;letter-spacing:1px;text-transform:uppercase;color:var(--tx3);margin-bottom:14px">Lerntools</div>
<div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px">
<div class="c ck" onclick="go('sales_mind')" style="text-align:center;padding:24px 16px"><div style="font-size:24px;font-weight:700;background:var(--grad);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:6px">3</div><div class="ct2">Zusammenfassung</div><div class="cd">Mindmaps</div></div>
<div class="c ck" onclick="go('sales_kart')" style="text-align:center;padding:24px 16px"><div id="ltSalesCards" style="font-size:24px;font-weight:700;background:var(--grad);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:6px">51</div><div class="ct2">Karteikarten</div><div class="cd">Klicken &amp; repetieren</div></div>
<div class="c ck" onclick="go('sales_quiz')" style="text-align:center;padding:24px 16px"><div id="ltSalesQuiz" style="font-size:24px;font-weight:700;background:var(--grad);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:6px">51</div><div class="ct2">Quiz</div><div class="cd">Mit Lernfortschritt</div></div>
<div class="c ck" onclick="go('sales_glossar')" style="text-align:center;padding:24px 16px"><div style="font-size:24px;font-weight:700;background:var(--grad);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin-bottom:6px">A–Z</div><div class="ct2">Glossar</div><div class="cd">Fachbegriffe</div></div></div></div>

<!-- KAP 1: EINORDNUNG VERKAUF -->
<div class="sec" id="sales_kap1"><h1>Einordnung Verkauf</h1><p class="sub">Kapitel 1 — Warum Sales, Marketing-Mix, Vertrieb, Segmente, Einkaufsprozesse, Kundentypen</p>
<div class="hl">Ob wir ein Produkt verkaufen, eine Dienstleistung anbieten oder bei der Geschäftsleitung um eine Gehaltserhöhung bitten — immer geht es darum, jemanden von «etwas» zu überzeugen. Im Gastgewerbe bleibt der professionelle Verkauf zu oft auf der Strecke.</div>
<div style="display:flex;gap:8px;margin:12px 0 4px"><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.add('open'))">Alle aufklappen</button><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.remove('open'))">Alle schliessen</button></div>
<div class="tl">

<div class="tl-item"><div class="tl-num tl-num-b">1</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Einleitung — Warum Sales im Gastgewerbe?</div><div class="tl-merksatz">«Wir verkaufen keine Zimmer — wir verkaufen Lösungen.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Es geht nicht darum, einem Gast am Tisch ein Getränk zu verkaufen. Vielmehr geht es um den <strong>Aufbau langfristiger Beziehungen</strong> zwischen Kundschaft und Dienstleistungsunternehmen — z.B. zwischen einer Firma und einem Hotel, einer Reiseagentur und einem Restaurant. Dabei ist es unerlässlich zu verstehen, wie der Einkauf auf Seite des Verhandlungsgegenübers funktioniert. Nur dann kann die Verkaufsperson in Verhandlungen bestehen.</div><div class="merksatz">Fallbeispiel Bellevue: Lisa Meier betont bei jedem Teammeeting: «Wenn die Novartis-Travel-Managerin bei uns bucht, kauft sie nicht einfach 50 Übernachtungen, sondern Zuverlässigkeit, schnellen Check-in für gestresste Geschäftsreisende und einen reibungslosen Abrechnungsprozess.»</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">2</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Gesamtkontext — Schnittstellen zu Marketing (4 Ps)</div><div class="tl-merksatz">«Sales gehört zu Place UND Promotion — nicht nur zu einem P.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Im strategischen Marketing unterscheidet man den Marketing-Mix in die sogenannten <strong>4 Ps</strong>: <strong>Product</strong> (Produktgestaltung, Sortiment, Marke), <strong>Price</strong> (Preisfestlegung, Strategie, Konditionen, Yield/Revenue), <strong>Place/Distribution</strong> (Absatzwege, Vertrieb, Logistik) und <strong>Promotion</strong> (Kommunikationsmix). Sales/Verkauf wird dabei primär dem <strong>Place</strong> und der <strong>Promotion</strong> zugeordnet.<br><br>Unter <strong>Place</strong> versteht man alle Entscheidungen und Massnahmen, die den Weg eines Produkts/einer Dienstleistung von der anbietenden zur verbrauchenden Person betreffen. Da wir ein Hotel nicht «liefern» können, bedeutet Sales in unserer Branche: die Kundschaft dazu bringen, in unserem Hotel zu buchen und die Dienstleistung vor Ort anzunehmen. Dazu gehören die langfristige Vertriebspolitik, die Wahl der Distributionskanäle, die Auswahl der richtigen Kundschaft und die Pflege der Vertriebs- und Gästebeziehungen.<br><br>Unter <strong>Promotion</strong> fällt der allgemeine Kommunikations-Mix — neben klassischer Werbung und Sponsoring sind hier der <strong>persönliche Verkauf</strong> und das <strong>Event-Marketing</strong> angesiedelt, also direkte Werkzeuge des Sales.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">3</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Direkter vs. indirekter Vertrieb</div><div class="tl-merksatz">«Farming = ernten was reinkommt. Hunting = aktiv neue Geschäfte jagen.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Direkter Vertrieb</strong> umschreibt alle Verkaufsaktivitäten ohne Zwischenhändler, <strong>indirekter Vertrieb</strong> dagegen die Aktivitäten unter Einbezug von Zwischenhändlern (z.B. Reisebüros, OTAs wie Booking.com).<br><br>Beim direkten Vertrieb unterscheidet man zwischen <strong>reaktivem Verkauf «Farming»</strong> (Anfragen bearbeiten, die von aussen kommen: Bankett-/Event-Abteilung, Rezeption, Service — man «erntet», was hereinkommt) und <strong>proaktivem Verkauf «Hunting»</strong> (aktive Neukundenakquise: Sales-/Account Management, Verkaufsabteilung, Aussendienst — man «jagt» neue Geschäfte).<br><br><strong>Vorteile des direkten Vertriebs:</strong> Direkte Kommunikation mit der Kundschaft → Loyalitätsaufbau. Unmittelbare Steuerung und Kontrolle. Keine Aufwände für Mittler-Gebühren, Provisionen, Kommissionen.<br><br><strong>Nachteile:</strong> Viele Märkte und Kundensegmente bleiben unbearbeitet (mangels Ressourcen). Sales-Mitarbeitende müssen gefunden, geschult und geführt werden. Der Betrieb muss die Vertriebskosten vorfinanzieren und das Erfolgsrisiko tragen.</div><div class="merksatz">Fallbeispiel Bellevue: Marc Brunner (Corporate Sales) arbeitet im proaktiven direkten Vertrieb — er besucht Firmen in der Region Zentralschweiz und verhandelt Firmenraten. Sophie Keller pflegt dagegen auch den indirekten Vertrieb: Verträge mit Tour Operators wie Kuoni und TUI, Kommissionsvereinbarungen mit Booking.com und Expedia. Die Rezeption betreibt reaktiven Verkauf: Walk-in-Gäste, Telefonanfragen, Upselling beim Check-in.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">4</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Markt- oder Verkaufssegmente</div><div class="tl-merksatz">«Segmentierungen variieren stark — es gibt keinen universellen Standard!»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Segmentierung</strong> bedeutet die Aufteilung eines Markts in Kundschafts- oder Gästegruppen nach bestimmten Kriterien, die dann separat bearbeitet werden. Neben sozioökonomischen Merkmalen (Alter, Geschlecht, Einkommen) spielen im Gastgewerbe besonders <strong>branchenspezifische Kriterien</strong> eine Rolle:<br><br>• <strong>Buchungsgrösse:</strong> Einzel- oder Gruppenbuchungen (z.B. ab 9/10 Zimmern = Gruppe)<br>• <strong>Aufenthaltszweck:</strong> Geschäftlich (Business) oder Freizeit/Privat (Leisure)<br>• <strong>Vertragsverhältnis:</strong> Lokal/international, mit/ohne Vertrag, Reiserichtlinien ja/nein<br><br>Die Segmentierung ist bei Hotelketten fast immer vorgegeben, unterscheidet sich aber je nach Unternehmen — IHG hat eine andere Einteilung als Marriott oder Radisson.</div><div class="merksatz">Merke: Entscheidend ist, dass Sie die Segmentierung Ihres Betriebs kennen und danach arbeiten.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">5</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Einkaufsprozesse — der Blick auf die Kundenseite</div><div class="tl-merksatz">«Wer Fristen verpasst oder falsche Tools nutzt, verliert das Geschäft — unabhängig von der Qualität.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Für Verkaufsmitarbeitende sind gründliche Kenntnisse der Abläufe auf Kundenseite unerlässlich. Die Einkaufsprozesse sind oft überraschend komplex, teuer und zeitaufwendig. Man trifft auf geschulte <strong>Einkaufs-Fachleute</strong> (Einkäufer:innen, Travel Manager), die ganz andere Anforderungen haben als die Gäste selbst.<br><br>Die zu beantwortenden <strong>Kernfragen</strong> über die Segmente/Kundschaft sind:<br>• <strong>Wie?</strong> — Wie läuft der Einkaufsprozess ab, in welchen Stufen?<br>• <strong>Wann?</strong> — Welche Fristen sind einzuhalten?<br>• <strong>Womit?</strong> — Welche Tools/Mittel werden eingesetzt?<br>• <strong>Wer?</strong> — Wer trifft die Entscheidungen bzw. ist daran beteiligt?</div><div class="merksatz">Merke: Jedes Segment hat seinen eigenen Einkaufsprozess. Es ist die zentrale Aufgabe der Verkaufsperson, diese Prozesse für die wichtigen Zielgruppen zu kennen und sicherzustellen, dass sich das Hotel daran hält.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">6</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Corporate Transient — Einzel-Geschäftsreisende</div><div class="tl-merksatz">«Managed Travel = Reiserichtlinien + RFP ab Mitte Jahr. Unmanaged = freie Hotelwahl, OTA-Preis.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Mit Reiserichtlinien (Managed Travel):</strong> Sobald ein Unternehmen an einem Ort ein höheres Geschäftsreiseaufkommen hat, versucht es, via Vertrag mit einem Hotel einen Preisnachlass zu verhandeln. Diese Vertragsverhandlungen sind je nach Firmengrösse sehr aufwendig und beginnen oft bereits <strong>Mitte des Kalenderjahres für das Folgejahr</strong>. Grosse Unternehmen führen diesen Einkaufsprozess als <strong>RFP</strong> (Request for Proposal) elektronisch durch, z.B. mit Tools wie Lanyon oder Nexus, oder beauftragen eine <strong>TMC</strong> (z.B. Amex GBT, BCD Travel, CWT). Diese Prozesse sind exakt einzuhalten — Abweichungen können zum Verlust des Vertrages führen. Reisende sind durch mehr oder weniger strikte Reiserichtlinien an die Hotelauswahl gebunden. Auch der Buchungsprozess kann an <strong>Konsortien</strong> (spezialisierte weltweit operierende Reisebüros) ausgelagert werden. Ist das Reisebüro auf dem Firmengelände und exklusiv tätig, spricht man von einem <strong>Implant</strong>.<br><br><strong>Ohne Vorgaben (Unmanaged Travel):</strong> Der Gast/Bucher ist nicht an Reiserichtlinien gebunden — die Hotelwahl ist seine individuelle Entscheidung. Viele orientieren sich an OTAs und buchen den tagesaktuellen Preis. Mitentscheidend sind oft Vielreise- oder Stammgastprogramme. Einige OTAs haben für KMU/SME spezielle Programme aufgelegt, damit auch kleinere Unternehmen ohne grosse Volumen an Nachlässe kommen.</div><div class="merksatz">Fallbeispiel Bellevue: Marc Brunner erhält im Juni eine RFP-Einladung von der Roche AG über Lanyon. Er muss bis zum 15. August die Raten eingeben, inklusive Last-Room-Availability-Garantie, Stornierungsbedingungen und Amenity-Paket. Die Frist ist eng — ein verspätetes Angebot bedeutet automatisch Ausschluss vom Vertrag.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">7</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Transient Leisure, Gruppen &amp; Airlines</div><div class="tl-merksatz">«Veranstalter = statische Katalogpreise, 9–18 Monate Vorlauf. OTAs = dynamisch.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Einzel-Freizeitreisende:</strong> Die touristische Marktstruktur bei Paketreisen folgt einer Kette: Gäste → Reisebüro (Retailer) → Veranstalter (Tour Operator) → Incoming Operator → Hotel. Die Einkaufsprozesse sind oft noch durch Katalogproduktion geprägt (langer Vorlauf, einmal gedruckt statisch). Bei Flugdestinationen müssen Veranstalter <strong>9–18 Monate im Voraus</strong> Flugkapazitäten einkaufen. Einzelfreizeitreisende buchen zunehmend selbst über OTAs — das Hotel muss auf diesen Portalen buchbar sein (12-monatige Verträge, Kommission) und gleichzeitig durch Marketing zur <strong>Direktbuchung</strong> überzeugen. Dieses Segment zeichnet sich durch <strong>dynamische Preise</strong> aus.<br><br><strong>Geschäftsreisegruppen / MICE:</strong> Ab ca. 10 Zimmern = Gruppe. Vielfältige Vorbereitungen nötig (TN-Absprache, Koordination, Zahlungsabwicklung). Oft über spezialisierte Agenturen (Cvent, Meetingselect). Strikte Einhaltung von Formaten und Fristen. Die Hotel-/Restaurantleistung ist oft nur ein Teil der Gesamtkosten.<br><br><strong>Freizeitreisegruppen / SMERF:</strong> Werden vom Veranstalter oft als Serie eingekauft (z.B. x Personen jeden Montag). Private Gruppen werden selten proaktiv akquiriert, eher über Werbung vermarktet.<br><br><strong>Airlines:</strong> Besonderes Geschäftsfeld nahe Flughafen. <strong>Crew-Aufenthalte</strong> sind regelmässig und planbar, mit Zusatzleistungen (Transfer, Wäsche). Langwieriger Einkaufsprozess. <strong>Layover</strong> ist ad-hoc-Geschäft bei Störungen — erfordert schnelle Reaktion der Operation.</div><div class="merksatz">Fallbeispiel Bellevue: Sophie Keller bereitet sich auf die ITB Berlin vor — 15 Termine mit Tour Operators (TUI, DER Touristik, Kuoni). Gleichzeitig betreut Marc die MICE-Anfrage der Swisscom für eine 3-tägige Kadertagung mit 80 Teilnehmenden. Die Anfrage kam über Cvent — er muss innerhalb von 48 Stunden ein detailliertes Angebot einreichen.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">8</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Persönlichkeitsmodelle — 4 Kundentypen</div><div class="tl-merksatz">«Sicherheit, Wirtschaftlichkeit, Prestige, Bequemlichkeit — jeden anders ansprechen!»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Persönlichkeitsmodelle werden eingesetzt, um Kund:innen einzuordnen, zu gruppieren und Massnahmen zu steuern. Die anzuwendenden Typisierungen werden in der Regel vom Unternehmen vorgegeben.<br><br><strong>Sicherheitstyp:</strong> Hat Angst vor Veränderungen, sucht Stabilität, zuverlässige Lieferanten und konstante Qualität. Wechselt ungern. Preis ist sekundär — Seriosität und Güte zählen. <em>Tipp:</em> Optimale Sicherheit bieten, bei zugesicherten Eigenschaften nie enttäuschen, Zertifikate betonen, persönliche Betreuung anbieten.<br><br><strong>Wirtschaftlichkeitstyp:</strong> Stark am Preis-Leistungs-Verhältnis interessiert, manchmal am niedrigsten Preis. Fragt nach Aktionen/Sonderangeboten. Geniesst das Preisgespräch. <em>Tipp:</em> Auf längeres Preisgespräch einstellen. Wenn nötig hart verhandeln — dieser Typ liebt eine ebenbürtige Gegenpartei.<br><br><strong>Prestigetyp:</strong> Versucht durch Einkäufe Ansehen zu gewinnen. Hohes Markenbewusstsein, sucht Profilierung. Status (Kleidung, Fahrzeug, Büro) ist wichtig. <em>Tipp:</em> Bewunderung/Anerkennung zeigen, Neuheiten zuerst anbieten, zu Events einladen. Titel verwenden, wenn vorhanden.<br><br><strong>Bequemlichkeitstyp:</strong> Liebt stabile, risikolose Verhältnisse und das Prinzip «Alles aus einer Hand». Wünscht Rundum-Service, Kontinuität, Zuverlässigkeit. <em>Tipp:</em> Jede Art von Arbeit abnehmen. Neues nur bei echtem Vorteil ohne Mehraufwand. Referenzen bereithalten.<br><br>Weitere Modelle: <strong>DISC/DISG</strong> (Dominanz, Initiative, Stetigkeit, Gewissenhaftigkeit) und <strong>Myers-Briggs Type Indicator (MBTI)</strong>.</div><div class="merksatz">Fallbeispiel Bellevue: Die Novartis-Travel-Managerin ist ein Sicherheitstyp — sie will Verlässlichkeit, immer den gleichen Check-in-Prozess und klare Eskalationswege. Marc betont Zertifizierungen und den persönlichen Ansprechpartner. Der Einkäufer einer Beratungsfirma ist ein Wirtschaftlichkeitstyp — er vergleicht jedes Jahr drei Hotels und verhandelt hart um Raten. Marc bereitet sich mit Zahlen zur Marktposition und Benchmarks vor.</div></div></div>

</div></div>

<!-- KAP 2: VERKAUFSGESPRÄCHE -->
<div class="sec" id="sales_kap2"><h1>Verkaufsgespräche</h1><p class="sub">Kapitel 2 — Kommunikation, Fragetechniken, 7 Phasen, FAB, Preisnennung, Abschluss, Einwände</p>
<div class="hl">Obwohl verbale Kommunikation im Verkaufsgespräch bewusst eingesetzt wird, ist ihre Gewichtung bei der Wahrnehmung überraschend gering: <strong>7% Worte/Inhalt, 38% Stimme/Tonfall, 55% Körpersprache.</strong></div>
<div style="display:flex;gap:8px;margin:12px 0 4px"><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.add('open'))">Alle aufklappen</button><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.remove('open'))">Alle schliessen</button></div>
<div class="tl">

<div class="tl-item"><div class="tl-num tl-num-b">1</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Verbale Kommunikation — 4-Ohren-Modell (Schulz von Thun)</div><div class="tl-merksatz">«Wer nur auf der Sachebene reagiert, übersieht die wahre Botschaft.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Jede Äusserung («Nachricht») kann aus <strong>vier unterschiedlichen Richtungen</strong> angesehen und gedeutet werden. Der Sender «spricht mit vier Schnäbeln» und der Empfänger «hört mit vier Ohren»:<br><br>• <strong>Sachebene:</strong> Die beschriebene Sache — «Worüber ich informiere»<br>• <strong>Selbstoffenbarungsebene:</strong> Was über die sprechende Person deutlich wird — «Was ich von mir selbst kundgebe»<br>• <strong>Beziehungsebene:</strong> Was über die Beziehung offenbart wird — «Was ich von dir halte oder wie wir zueinanderstehen»<br>• <strong>Appellebene:</strong> Wozu der Empfänger veranlasst werden soll — «Wozu ich dich veranlassen möchte»</div><div class="merksatz">Beispiel: Ein Firmenkunde sagt: «Ihr Mitbewerber hat mir einen besseren Preis angeboten.» — Sachebene: Ein anderes Hotel ist günstiger. Selbstoffenbarung: Ich bin preisbewusst. Beziehung: Ich erwarte Entgegenkommen. Appell: Senken Sie Ihren Preis!</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">2</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Nonverbale Kommunikation</div><div class="tl-merksatz">«Die ersten 30 Sekunden entscheiden — der erste Eindruck haftet über Jahre.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Nonverbale Kommunikation wird überwiegend durch <strong>Körpersprache</strong> ausgedrückt, aber auch durch <strong>paraverbale Kommunikation</strong> (Stimmeigenschaften, Sprechverhalten, Lachen, Seufzen, Räuspern).<br><br>Bei Neukund:innen entscheiden bereits die <strong>ersten 30 Sekunden</strong>, ob das Gegenüber Sie spontan mag und ob die Chemie stimmt. Der erste Eindruck ist enorm wichtig und haftet häufig über viele Jahre — die Korrektur einmal abgespeicherter Eindrücke ist sehr schwierig und aufwendig.<br><br>Die <strong>Körpersprache (Kinesik)</strong> kann nur schwer «lügen», da viele Aspekte unbewusst und unkontrolliert ablaufen. Wer sie entschlüsseln kann, hat eine exzellente Voraussetzung, sich in seine Kund:innen hineinzuversetzen und deren Motive zu erkennen.<br><br>Die wichtigsten Signale: Gestik &amp; Motorik · Körperhaltung · Mimik · Blickkontakt · Räumliches Verhalten · Paraverbale Kommunikation · Kleidung, Frisur, Statussymbole.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">3</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Fragetechniken — «Wer fragt, der führt»</div><div class="tl-merksatz">«Fragen und Zuhören sind Ihre wichtigsten Verkaufsinstrumente — und sie kosten nichts!»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Mit Fragen können Sie Einwände geschickt behandeln, Meinungen beeinflussen, Informationen gewinnen und den Gesprächsverlauf bestimmen.<br><br><strong>Offene Fragen (W-Fragen):</strong> Wer, wie, warum etc. Gewinnen Informationen, halten Gespräche im Fluss, bauen Vertrauen auf. Ideal für Bedarfsanalyse und Gesprächseröffnung. Bsp: «Welche Anforderungen hat Ihre Tagung?»<br><br><strong>Geschlossene Fragen:</strong> Ja/Nein-Antwort. Engen Reaktionsmöglichkeiten stark ein und erleichtern dem Gegenüber, Gespräche schnell zu beenden. <em>Nur bewusst taktisch einsetzen!</em><br><br><strong>Alternativfragen:</strong> Mischung offen/geschlossen. Bietet nur Varianten der Zustimmung — keine Nein-Option. Bsp: «Wollen Sie die VA in KW 50 oder 51 platzieren?» Eignet sich auch zum Abschluss.<br><br><strong>Suggestivfragen:</strong> Keine echte Frage — will Meinung vorgeben. Manipulierender Charakter offensichtlich. <em>Sehr vorsichtig einsetzen!</em><br><br><strong>Gegenfragen:</strong> Reagieren auf Einwände, gewinnen Zeit, fordern das Gegenüber, seine Aussage klarer darzulegen. Bsp: «Ist der Preis nicht zu hoch?» — «Im Verhältnis wozu?»<br><br><strong>Ermittlungsfragen:</strong> Offene Frage, wesentlicher Bestandteil der Bedarfsanalyse. Bsp: «Für wie viele Mitarbeitende benötigen Sie Übernachtungen?»<br><br><strong>Rhetorische Fragen:</strong> Keine Antwort erwartet. Steuert Gespräch Richtung Zielerreichung.<br><br><strong>Ja-Fragen:</strong> Lässt fast nur «Ja» als Antwort zu. Aneinandergereiht = <strong>«Ja-Strasse»</strong> als Abschlusstechnik.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">4</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Die 7 Phasen des Verkaufsgesprächs</div><div class="tl-merksatz">«Vorbereitung → Warm-up → Bedarfsanalyse → Präsentation → Preis → Abschluss → Nachbearbeitung»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Phase 1 — Vorbereitung:</strong> Terminvereinbarung &amp; Bestätigung. Recherche (Bestandskund:innen: Kundenhistorie, Umsätze, Reklamationen; Neukund:innen: Internet, Medien, LinkedIn). Unterlagen bereitstellen. Gesprächsziele definieren. Rückversicherung am Tag davor.<br><br><strong>Phase 2 — Warm-up / Begrüssung:</strong> Bei Kaltakquise zunächst nach der richtigen <strong>Ansprechperson (ASP)</strong> fragen. Dann Begrüssung, Vorstellung, Smalltalk. Doppelter Aufbau: Beziehungsaufbau (sympathisch, freundlich, unaufdringlich) und Kompetenzaufbau (Produkt-/Marktkenntnis, Berufserfahrung). Signale der Kund:innen beachten!<br><br><strong>Phase 3 — Bedarfsanalyse:</strong> Bedürfnisse der Kundschaft herausfinden — bewusste und noch unbewusste. Vor allem <strong>offene Fragen</strong> verwenden (Suggestivfragen nicht geeignet!). <strong>Trichtermodell:</strong> Mit breiten Fragen beginnen, schrittweise einschränken. Verkaufsperson: fragen, zuhören, steuern, Beraterfunktion.<br><br><strong>Phase 4 — Produktpräsentation:</strong> Produktmerkmale mit Bedürfnissen aus der Bedarfsanalyse verknüpfen. Kern: <strong>Nutzenargumentation (FAB)</strong>. Kaufsignale beachten. Verkaufsmittel einsetzen.<br><br><strong>Phase 5 — Preisnennung:</strong> Erst unmittelbar vor dem Abschluss. <strong>Sandwich-Methode</strong> anwenden (siehe nächste Abschnitte).<br><br><strong>Phase 6 — Verkaufsabschluss:</strong> Muss zwingend durch die Verkäufer:in eingeleitet werden. Kaufsignale erkennen! Abschlusstechniken einsetzen.<br><br><strong>Phase 7 — Nachbearbeitung:</strong> Dankesnachricht mit besprochenen Punkten und nächsten Schritten. Information an alle betroffenen Abteilungen. Kundenprofil pflegen (PMS, Verkaufssoftware). Follow-ups und Erinnerungen setzen.</div><div class="merksatz">Merke: Die Nachbearbeitung entscheidet über das Folgegeschäft! Die beste Verkaufspräsentation ist wertlos, wenn danach keine Dankesnachricht kommt, das Angebot verspätet eingeht oder die Informationen nicht an die operative Abteilung weitergegeben werden.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">5</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Nutzenargumentation — FAB-Technik</div><div class="tl-merksatz">«Es wird nie das Produkt gekauft — es wird immer der Nutzen/Gewinn erworben.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Eine kundschaftsorientierte Argumentation ist weit mehr als das Aufzählen positiver Produktmerkmale. Nicht jedes Argument ist für jede Klientel passend! Nennen Sie nur die Argumente, welche die Kundschaft braucht, und schildern Sie gleichzeitig, welchen Nutzen sie davon hat.<br><br><strong>FAB = Feature – Advantage – Benefit:</strong><br>• <strong>Merkmal (Feature):</strong> Sachliche Produkteigenschaft. Bsp: «Unsere Rezeption ist 24 Stunden besetzt.»<br>• <strong>Vorteil (Advantage):</strong> Allgemeiner Nutzen des Merkmals. Bsp: «Sie können jederzeit anreisen.»<br>• <strong>Nutzen (Benefit):</strong> Individueller Kundennutzen. Bsp: «Sie sind terminlich viel flexibler und brauchen sich bei Verspätungen keine Gedanken zu machen.»<br><br>Wichtig: Immer nur <strong>ein Merkmal, ein Vorteil und ein Nutzen</strong> in einer Kette. Überlegen Sie sich zuerst, welchen Nutzen Sie «verkaufen» möchten!<br><br><strong>Kaufmotivatoren:</strong><br>Sachlich = «Mehr»: mehr Effizienz, Gewinn, Produktion, Motivation, Zeit, Sicherheit.<br>Emotional = «Weniger»: weniger Aufwand, Risiko, Kosten, Stress, Sorgen, Konflikte.</div><div class="hlr"><strong>Falsch:</strong> «Dieses Zimmer hat ein Queen-Size-Bett.» (nur Merkmal, kein Nutzen)<br><strong>Richtig:</strong> «In diesem Queen-Size-Bett haben Sie genug Platz und schlafen gut, sodass Sie morgen ausgeruht zu Ihrer Besprechung gehen.» (Merkmal + Vorteil + Nutzen)</div><div class="merksatz">Fallbeispiel Bellevue: Marc präsentiert der Novartis: Merkmal: «Express-Check-in mit App.» Vorteil: «Ihre MA können direkt aufs Zimmer — ohne Wartezeit.» Nutzen: «Das spart nach langen Anreisetagen wertvolle Zeit und reduziert Reisestress — und Sie erhalten weniger Beschwerden.» Damit spricht er «mehr Zeit» (sachlich) und «weniger Stress» (emotional) an.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">6</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Preisnennung — Sandwich-Methode</div><div class="tl-merksatz">«Nennen Sie den Preis niemals alleine — immer wohldosiert verpackt in Vorteile!»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Das Preisgespräch soll immer erst <strong>unmittelbar vor dem Abschluss</strong> erfolgen. Die Kundschaft muss ihren Bedarf erkannt haben, ihre persönlichen Vorteile sehen und den Kaufwunsch empfinden.<br><br><strong>Psychologische Preisminimierung:</strong> Das Nennen des reinen Preises ohne Erklärung ist für Verkäufer:innen fatal! Das Wort «kostet» schafft negative Assoziationen (Telefonkosten, Mietkosten, Heizkosten).<br><br><strong>Die Sandwich-Methode:</strong> Verpacken Sie den Preis in die Mitte von Vorteilen: <strong>1–3 Vorteile → PREIS → 1–3 Vorteile</strong>. Dadurch wird der Preis psychologisch minimiert. Nach der Preisnennung <strong>keine Sprechpause</strong> entstehen lassen — die Wirkung der Minimierung würde zerstört.</div><div class="hlr"><strong>So NICHT:</strong> «Die Übernachtung kostet 262.30 CHF.» → Reizwort «kostet» + nackter Preis = psychologischer GAU.<br><br><strong>Richtig (Sandwich):</strong> «Die Übernachtung im schönen grossen Einzelzimmer mit Blick auf den See bieten wir Ihnen für CHF 262.30 an, das inkludiert auch das reichhaltige Frühstück vom Buffet und die City Tax.»</div><div class="merksatz">Wenn die Kundschaft nochmals nach dem Preis fragt (Beweis, dass das Sandwich funktioniert hat!), antworten Sie erneut mit einem reduzierten Sandwich: «Im genannten Endpreis sind Nebenleistungen und Extraausstattungen bereits enthalten, sodass Sie mit keinerlei zusätzlichen Kosten rechnen müssen.»</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">7</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kaufsignale &amp; Abschlusstechniken</div><div class="tl-merksatz">«Kaufsignale NIEMALS übersehen — unnötige Argumente können den Kaufwunsch ersticken!»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Kaufsignale</strong> sind verbale und körpersprachliche Zeichen, die darauf hindeuten, dass eine Entscheidung gefällt wurde oder kurz bevorsteht. Die Kundschaft beschäftigt sich mit Fakten, die erst nach dem Abschluss Bedeutung haben:<br><br>• Direkter Kaufwunsch wird geäussert<br>• Fragen nach dem «Danach» (Kundendienst, Garantie, Betreuung)<br>• Beschäftigung mit Details (Zubehör, Ausstattung, Preis)<br>• Immer öftere Zustimmung und Identifizierung mit dem Produkt<br>• Fragen nach Bewährung und Referenzen<br>• Hinzuziehen weiterer Personen<br>• Zustimmendes Nicken, starkes Interesse in Körperhaltung und Mimik<br><br><strong>Abschlusstechniken:</strong> Probeabschluss («Angenommen, Sie haben sich entschlossen...»), Zusammenfassung der bestätigten Argumente (stärkstes am Schluss), <strong>Ja-Strasse</strong> (eleganteste Form — kein Druckgefühl), Empfehlungstechnik, Alternativtechnik (zwei positive Alternativen), direkte Bestätigung (nur bei eindeutiger Kaufbereitschaft).</div><div class="merksatz">Warnung: Wer nach erkennbaren Kaufsignalen weiter argumentiert statt zum Abschluss überzugehen, riskiert die Rückentwicklung des Kaufwunsches. Unnötige Argumente können neue Zweifel wecken!</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">8</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Einwandbehandlung — 5 Schritte</div><div class="tl-merksatz">«NEIN = Noch Etwas Input Nötig. Begrüssen Sie Einwände!»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Einwände und Fragen sind normale Bestandteile einer Verhandlung. Begrüssen Sie Einwände — sie fördern die Kommunikation und signalisieren Interesse!<br><br>Verwandeln Sie in <strong>fünf Schritten</strong> einen Einwand in Zustimmung:<br><strong>1. Verständnis zeigen</strong> → <strong>2. Nachfragen</strong> → <strong>3. FAB zum Einwand</strong> → <strong>4. Rückversichern</strong> → <strong>5. Erneuter Abschlussversuch</strong><br><br>Diese Abfolge funktioniert, weil Sie mit den Schritten 1 und 2 «die Luft herauslassen» und das Gegenüber auf die rationale Ebene zurückholen. Erst in Schritt 3 versuchen Sie eine sachliche Klärung. Schritt 4 prüft, ob die Angelegenheit bereinigt ist. Schritt 5 ist zwingend!<br><br><strong>Tipps:</strong> Auf alle denkbaren Einwände vorbereiten. Aufmerksam zuhören. Nie unterbrechen. Vorwand im Einwand erkennen. Korrekt, höflich, ruhig, sachlich bleiben. Nicht als Besserwisser auftreten. Wissen Sie keine Antwort, geben Sie es offen zu.</div><div class="merksatz">Fallbeispiel Bellevue: Travel Managerin: «Ihr Hotel hat keinen Pool.» — 1. «Das verstehe ich — Entspannung nach einem langen Arbeitstag ist wichtig.» 2. «Nutzen Ihre Reisenden den Pool aktiv zum Schwimmen oder eher zur Entspannung?» 3. «Unser Wellnessbereich bietet genau diese Entspannung — mit persönlicher Betreuung.» 4. «Wäre das eine gute Alternative?» 5. «Dann lassen Sie uns die Konditionen finalisieren…»</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">9</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Preisverhandlung — 5 Strategien</div><div class="tl-merksatz">«Einfach den Preis senken ist kein Verhandeln — es geht um Profitabilität!»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Preisverhandlungen sind normal. Eine der bekanntesten Einkaufsstrategien: niemals das erste Angebot akzeptieren. Kennen Sie Ihren Verhandlungsspielraum und wissen Sie, ab wann Sie auf das Geschäft verzichten.<br><br><strong>1. Nutzenargumentation:</strong> Stärkste FABs wiederholen. Evtl. einen «Reserve-Nutzen» einsetzen. <em>Kostet nichts — immer zuerst versuchen!</em><br><strong>2. Nutzenerhöhung durch Zugaben:</strong> Etwas inkludieren, das für die Kundschaft hohen Nutzen hat, aber wenig kostet: Late Check-out, Spa-Zugang, Apéro, günstigere Zahlungskonditionen.<br><strong>3. Preis- und Leistungskürzung:</strong> Preis reduzieren, aber auch Leistung/Service kürzen. Was hat wenig Bedeutung für die Kundschaft?<br><strong>4. Preissenkung:</strong> Letzte Lösung — Preis bei voller Leistung senken. Nur innerhalb des Verhandlungsspielraums!<br><strong>5. Kein Abschluss:</strong> Diese Möglichkeit vorab einplanen. Nicht persönlich nehmen. Sachlich, höflich, professionell bleiben. Kontakt für zukünftiges Geschäft erhalten.</div></div></div>

</div></div>

<!-- KAP 3: VERKAUFSPLANUNG -->
<div class="sec" id="sales_kap3"><h1>Verkaufsplanung</h1><p class="sub">Kapitel 3 — Verkaufsmassnahmen, Analyse, Pareto, ABC, 6W-Ziele, Budget</p>
<div class="hl">Die Verkaufsplanung verbindet <strong>Analyse</strong> (wo stehen wir?) mit <strong>Zielen</strong> (wo wollen wir hin?) und konkreten <strong>Massnahmen</strong> (wie kommen wir dahin?).</div>
<div style="display:flex;gap:8px;margin:12px 0 4px"><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.add('open'))">Alle aufklappen</button><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.remove('open'))">Alle schliessen</button></div>
<div class="tl">

<div class="tl-item"><div class="tl-num tl-num-b">1</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Verkaufsmassnahmen — Wege zur Kundschaft</div><div class="tl-merksatz">«Von Telefonat bis Tradeshow — jede Massnahme hat ihren Zweck und ihr Segment.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Im Hotel- und Gaststättengewerbe finden sich folgende Verkaufsmassnahmen:<br><br><strong>Telefonat:</strong> Aktiv: Terminvereinbarung, Nachfassen, Einladung zu Events, Neukundengewinnung. Nicht erlaubt bei Privatpersonen auf der Robinsonliste! Passiv/reaktiv: Anrufe der Kund:innen (Reservierung, Hotline, Reklamation).<br><br><strong>Soziale Medien:</strong> Primär Kommunikationskanal (Kontaktpflege, Gästekommentare, Beschwerden). Noch keine direkten Verkaufskanäle. LinkedIn/Xing wichtiger als Facebook. Contentmarketing: Fachartikel bereitstellen — unaufdringlich, langfristig, authentisch.<br><br><strong>Pitch / Elevator Pitch:</strong> Pitch = persönliche Präsentation zur Angebotsabgabe nach Briefing. Muss einprägsam sein! Elevator Pitch (30–60 Sek.): «Für Sie (Zielgruppe) und Ihr (Problem) ist (Produkt) eine (Kategorie) mit (Hauptvorteil). Im Vergleich zum Wettbewerb hebt es sich ab, weil (Einzigartigkeit).»<br><br><strong>Hausführungen:</strong> Spontan: Immer vorbereitet sein! 2–3 Zimmer + 1 VA-Raum bereithalten. Angemeldet: Umfang absprechen, Zimmer blocken, verschiedene Kategorien zeigen, höhere Etage mit Aussicht.<br><br><strong>Kundenveranstaltungen &amp; Fam-Trips:</strong> Events (Jubiläen, Eröffnungen, kulturelle VAs) für Kundenbindung + informelle Kontakte. Fam-Trips = kostenlose Studienreisen für Reisebüromitarbeitende — Präsentation muss einprägsam sein!<br><br><strong>Sales-Blitz:</strong> Kurze, intensive Verkaufskampagne in einem bestimmten Gebiet. Max. 5 Min. pro Besuch, eine Kernaussage, Infobeschaffung. Ergebnisse am Ende des Tages an das Hotelteam.<br><br><strong>Road Show / Tournee:</strong> Serie von Veranstaltungen in grösseren Städten, mehrere Anbieter gemeinsam. Aufwendig in der Vorbereitung.<br><br><strong>Tradeshows / Messen:</strong> IMEX (MICE), IBTM (Corporate), WTM (Tour Operator), ILTM (Luxus), ITB Berlin (global). Teilnahme kostspielig — messbare Ziele nötig! Nachbereitung einplanen.</div><div class="merksatz">Fallbeispiel Bellevue — Jahresplan: Januar: Sales-Blitz Zürich (Marc, 40 Firmenbesuche). März: ITB Berlin (Sophie, 15 Termine). Mai: Kundenveranstaltung «Gourmet Evening». Juni: RFP-Saison. September: IMEX Frankfurt. November: Fam-Trip für Reisebüros. Laufend: Telemarketing (2h/Woche), LinkedIn-Content, Hausführungen.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">2</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Planung in 5 Schritten &amp; Analyse</div><div class="tl-merksatz">«Analyse → Ziele → Strategie → Massnahmen → Budget»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Zur Leitung einer Verkaufsabteilung gehört die mittel- und langfristige Verkaufsplanung in fünf Schritten: <strong>1. Analyse → 2. Verkaufsziele → 3. Verkaufsstrategie → 4. Verkaufsmassnahmen → 5. Budget (-kontrolle)</strong>.<br><br><strong>Pareto-Regel (80/20):</strong> 80% der Ergebnisse werden mit 20% des Gesamtaufwandes erreicht. Im Verkauf: 20% der Kunden generieren 80% des Umsatzes.<br><br><strong>ABC-Analyse:</strong> Teilt Kunden/Produkte in drei Klassen nach absteigender Bedeutung: <strong>A-Kunden</strong> = höchste Umsatzbedeutung, intensivste Betreuung. <strong>B-Kunden</strong> = mittlere Bedeutung, Potenzial für A. <strong>C-Kunden</strong> = geringste Umsatzbedeutung, standardisierte Betreuung, oft grösste Anzahl.<br><br><strong>Weitere Analysekriterien</strong> (über Logiumsatz/Übernachtungen hinaus): F&amp;B-Umsatz · Anreisetag/Saison · Kosten/Ertrag/Buchungsweg · Stornierungen/Wash · Klumpenbildung · Zahlungsdisziplin · Anteil am Gesamtreiseumsatz einer Firma · Anzahl Mitbewerber · Anteil Neukundschaft vs. Bestandskundschaft.</div><div class="merksatz">Fallbeispiel Bellevue: Lisa analysiert die 150 Firmenkunden: A-Kunden (12 Firmen, 8%) generieren 65% des Corporate-Umsatzes (Novartis 480 RNs, Roche 320 RNs) → persönliche Betreuung durch Marc. B-Kunden (28 Firmen, 19%) = 25% → halbjährlicher Kontakt, Ziel: Entwicklung zu A. C-Kunden (110 Firmen, 73%) = 10% → standardisierte Betreuung via E-Mail-Newsletter.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">3</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Verkaufsziele — 6W-Raster &amp; Budget</div><div class="tl-merksatz">«Was? Wieviel? Wem? Wann? Wo? Wer? — Unmissverständliche Zielformulierung.»</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Zielsetzungen müssen fair, erreichbar, messbar und realisierbar sein (SMART). Das <strong>6W-Raster</strong> hilft, Ziele konkret zu definieren:<br><br>• <strong>Was:</strong> Zielinhalt (Umsatz, RNs, Gewinn, GOP, RevPAR, Neukund:innen)<br>• <strong>Wieviel:</strong> Quantifizierung (absolute Zahl, CHF, %)<br>• <strong>Wem:</strong> Zielsegment (Firmen, Tagungsgeschäft, Hochzeitsanlässe)<br>• <strong>Wann:</strong> Zielperiode (bis Ende Jahr, bis 20. September)<br>• <strong>Wo:</strong> Geographischer Markt (Schweiz, Luzern, Region ZH)<br>• <strong>Wer:</strong> Verantwortlichkeit (Herr XY, Verkaufsabteilung)<br><br><strong>Primäre Verkaufsplanung</strong> (nach aussen): Detaillierte Verkaufsziele heruntergebrochen nach Produkten, Kundengruppen, Regionen und Zeiträumen + Einsatzplanung → Sales &amp; Marketingplan.<br><strong>Sekundäre Verkaufsplanung</strong> (nach innen): Organisation, Personalplanung, Weiterbildung, Entlöhnung, Verkaufsmittel.<br><br><strong>Budget-Positionen:</strong> Personal (fix/variabel, Schulungen, Incentives) · Reisekosten (Kundenbesuche, Messen, Blitze) · Büro &amp; Verwaltung (CRM-Software, Kommunikation) · Massnahmen (Messegebühren, Verkaufsaktionen, Verkaufsmittel).</div><div class="merksatz">Fallbeispiel Bellevue — Verkaufsziel mit 6W: Was: Room Nights Corporate. Wieviel: 8'500 RNs (+12%). Wem: Corporate Transient. Wann: bis 31. Dezember. Wo: Quellmärkte CH und DE. Wer: Marc Brunner. Budget: CHF 448'000 (ca. 3.5% des Gesamtumsatzes).</div></div></div>

</div></div>

<!-- ZUSAMMENFASSUNG -->
<div class="sec" id="sales_mind"><h1>Zusammenfassung</h1><p class="sub">Sales — Alle 3 Kapitel auf einen Blick</p>
<div class="mm"><div class="mm-center"><div class="mm-hub" style="border-color:var(--ac);color:var(--ac);background:var(--al)">Sales</div></div>
<div class="mm-branches">
<div class="mm-branch" style="background:var(--al);border:1.5px solid var(--ac)"><h3 style="color:var(--ac)">1. Einordnung</h3><ul style="color:var(--ac)"><li>4 Ps: Place &amp; Promotion</li><li>Direkt vs. Indirekt</li><li>Farming vs. Hunting</li><li>5 Hauptsegmente</li><li>4 Einkaufs-Kernfragen</li><li>4 Kundentypen</li></ul></div>
<div class="mm-branch" style="background:var(--gl);border:1.5px solid var(--g)"><h3 style="color:var(--g)">2. Verkaufsgespräch</h3><ul style="color:var(--g)"><li>7% / 38% / 55%</li><li>4-Ohren-Modell</li><li>7+ Fragetechniken</li><li>7 Phasen</li><li>FAB-Technik</li><li>Sandwich-Methode</li><li>5 Schritte Einwand</li></ul></div>
<div class="mm-branch" style="background:var(--s2);border:1.5px solid var(--tx3)"><h3>3. Verkaufsplanung</h3><ul><li>11 Verkaufsmassnahmen</li><li>5 Planungsschritte</li><li>Pareto 80/20</li><li>ABC-Analyse</li><li>6W-Raster</li><li>Primär vs. Sekundär</li><li>Budget</li></ul></div>
</div></div>
</div>

<!-- KARTEIKARTEN -->
<div class="sec" id="sales_kart"><h1>Karteikarten</h1><p class="sub"><span id="salesfcCount">0</span> Karten — klicke zum Umdrehen</p>
<div class="fcc" id="salesfcc"></div>
<div class="fd"><div class="fc" id="salesfc" onclick="this.classList.toggle('fl')"><div class="ff ffr"><div class="fq" id="salesfcq"></div><div class="fh">Klicke zum Umdrehen</div></div><div class="ff ffb"><div class="fa" id="salesfca"></div></div></div></div>
<div class="fb"><button onclick="fcPrev()">Zurück</button><button onclick="fcShuffle()">Mischen</button><button class="bp1" onclick="fcNext()">Nächste</button></div>
<div style="text-align:center;margin-top:10px;font-size:11px;color:var(--tx3)" id="salesfcPool"></div>
<div id="salesfcList" style="display:none;margin-top:16px"></div>
</div>

<!-- QUIZ -->
<div class="sec" id="sales_quiz"><h1>Quiz</h1><p class="sub">Alle Fragen werden wiederholt bis du sie kannst</p>
<div id="salesqStats" style="margin-bottom:20px">
<div style="display:flex;gap:8px;margin-bottom:14px;flex-wrap:wrap">
<div class="qsc" style="flex:1;min-width:70px"><div class="qsn" id="salesqTotR" style="color:var(--g)">0</div><div class="qsl">Total richtig</div></div>
<div class="qsc" style="flex:1;min-width:70px"><div class="qsn" id="salesqTotW" style="color:var(--r)">0</div><div class="qsl">Total falsch</div></div>
<div class="qsc" style="flex:1;min-width:70px"><div class="qsn" id="salesqTotP" style="color:var(--ac)">0%</div><div class="qsl">Erfolgsquote</div></div>
</div>
<div style="font-size:12px;color:var(--tx3);margin-bottom:6px">Lernerfolg</div>
<div style="display:flex;gap:4px;margin-bottom:4px;align-items:center"><div style="width:10px;height:10px;border-radius:50%;background:var(--g);flex-shrink:0"></div><div style="font-size:12px;color:var(--tx2);width:70px">Sicher</div><div style="flex:1;height:8px;background:var(--s2);border-radius:4px;overflow:hidden"><div id="salesqBarG" style="height:100%;background:var(--g);border-radius:4px;transition:width .5s;width:0%"></div></div><div style="font-size:12px;color:var(--tx2);width:30px;text-align:right" id="salesqBarGn">0</div></div>
<div style="display:flex;gap:4px;margin-bottom:4px;align-items:center"><div style="width:10px;height:10px;border-radius:50%;background:var(--am);flex-shrink:0"></div><div style="font-size:12px;color:var(--tx2);width:70px">Wackelig</div><div style="flex:1;height:8px;background:var(--s2);border-radius:4px;overflow:hidden"><div id="salesqBarO" style="height:100%;background:var(--am);border-radius:4px;transition:width .5s;width:0%"></div></div><div style="font-size:12px;color:var(--tx2);width:30px;text-align:right" id="salesqBarOn">0</div></div>
<div style="display:flex;gap:4px;margin-bottom:4px;align-items:center"><div style="width:10px;height:10px;border-radius:50%;background:var(--r);flex-shrink:0"></div><div style="font-size:12px;color:var(--tx2);width:70px">Unsicher</div><div style="flex:1;height:8px;background:var(--s2);border-radius:4px;overflow:hidden"><div id="salesqBarR" style="height:100%;background:var(--r);border-radius:4px;transition:width .5s;width:0%"></div></div><div style="font-size:12px;color:var(--tx2);width:30px;text-align:right" id="salesqBarRn">0</div></div>
<div style="display:flex;gap:4px;align-items:center"><div style="width:10px;height:10px;border-radius:50%;background:var(--tx3);flex-shrink:0"></div><div style="font-size:12px;color:var(--tx2);width:70px">Noch offen</div><div style="flex:1;height:8px;background:var(--s2);border-radius:4px;overflow:hidden"><div id="salesqBarX" style="height:100%;background:var(--tx3);border-radius:4px;transition:width .5s;width:100%"></div></div><div style="font-size:12px;color:var(--tx2);width:30px;text-align:right" id="salesqBarXn">0</div></div>
</div>
<div class="pb"><div class="pf" id="salesqP"></div></div><div class="pt" id="salesqPT">Frage 1</div>
<div id="salesqC"></div>
<div style="text-align:center;margin-top:14px">
<button class="bp1" id="salesqN" onclick="salesqNx()" style="display:none">Nächste Frage</button>
<button class="bp1" id="salesqRS" onclick="salesqSt()" style="display:none">Weiter üben</button>
<button id="salesqReset" onclick="salesqReset()" style="display:none;margin-left:8px">Fortschritt zurücksetzen</button>
</div></div>

<!-- GLOSSAR -->
<div class="sec" id="sales_glossar"><h1>Glossar</h1><p class="sub">Fachbegriffe im Sales</p>
<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:8px">
<div class="c" style="padding:12px 16px"><strong>FAB</strong> <span style="color:var(--tx2)">— Feature-Advantage-Benefit. Merkmal → Vorteil → Nutzen.</span></div>
<div class="c" style="padding:12px 16px"><strong>RFP</strong> <span style="color:var(--tx2)">— Request for Proposal. Elektronische Ausschreibung für Hotelverträge.</span></div>
<div class="c" style="padding:12px 16px"><strong>TMC</strong> <span style="color:var(--tx2)">— Travel Management Company (z.B. Amex GBT, BCD, CWT).</span></div>
<div class="c" style="padding:12px 16px"><strong>OTA</strong> <span style="color:var(--tx2)">— Online Travel Agency (z.B. Booking.com, Expedia, HRS).</span></div>
<div class="c" style="padding:12px 16px"><strong>MICE</strong> <span style="color:var(--tx2)">— Meetings, Incentives, Conventions, Exhibitions.</span></div>
<div class="c" style="padding:12px 16px"><strong>SMERF</strong> <span style="color:var(--tx2)">— Social, Military, Educational, Religious, Fraternal.</span></div>
<div class="c" style="padding:12px 16px"><strong>Konsortium</strong> <span style="color:var(--tx2)">— Weltweit operierendes Reisebüro für Firmenbuchungen.</span></div>
<div class="c" style="padding:12px 16px"><strong>Implant</strong> <span style="color:var(--tx2)">— Reisebüro auf dem Firmengelände, exklusiv für ein Unternehmen.</span></div>
<div class="c" style="padding:12px 16px"><strong>Allotment</strong> <span style="color:var(--tx2)">— Zimmerkontingent für Tour Operator.</span></div>
<div class="c" style="padding:12px 16px"><strong>Farming</strong> <span style="color:var(--tx2)">— Reaktiver Verkauf (ernten was reinkommt).</span></div>
<div class="c" style="padding:12px 16px"><strong>Hunting</strong> <span style="color:var(--tx2)">— Proaktiver Verkauf (aktiv jagen).</span></div>
<div class="c" style="padding:12px 16px"><strong>Sandwich-Methode</strong> <span style="color:var(--tx2)">— Vorteile → Preis → Vorteile. Psychologische Preisminimierung.</span></div>
<div class="c" style="padding:12px 16px"><strong>Ja-Strasse</strong> <span style="color:var(--tx2)">— Aneinandergereihte Ja-Fragen als Abschlusstechnik.</span></div>
<div class="c" style="padding:12px 16px"><strong>Kinesik</strong> <span style="color:var(--tx2)">— Wissenschaft der Körpersprache.</span></div>
<div class="c" style="padding:12px 16px"><strong>ABC-Analyse</strong> <span style="color:var(--tx2)">— Kunden in A (Top), B (Mitte), C (Basis) einteilen.</span></div>
<div class="c" style="padding:12px 16px"><strong>Pareto</strong> <span style="color:var(--tx2)">— 80/20-Regel: 80% Ergebnis von 20% Aufwand.</span></div>
<div class="c" style="padding:12px 16px"><strong>6W-Raster</strong> <span style="color:var(--tx2)">— Was, Wieviel, Wem, Wann, Wo, Wer.</span></div>
<div class="c" style="padding:12px 16px"><strong>RN</strong> <span style="color:var(--tx2)">— Room Night. Eine Zimmerbelegung für eine Nacht.</span></div>
<div class="c" style="padding:12px 16px"><strong>LRA</strong> <span style="color:var(--tx2)">— Last Room Availability. Letztes Zimmer zum Firmenpreis.</span></div>
<div class="c" style="padding:12px 16px"><strong>Sales-Blitz</strong> <span style="color:var(--tx2)">— Intensive Kurzverkaufskampagne (max. 5 Min./Besuch).</span></div>
<div class="c" style="padding:12px 16px"><strong>Elevator Pitch</strong> <span style="color:var(--tx2)">— 30–60 Sek. Verkaufsvortrag.</span></div>
<div class="c" style="padding:12px 16px"><strong>Fam-Trip</strong> <span style="color:var(--tx2)">— Kostenlose Studienreise für Reisebüro-Mitarbeitende.</span></div>
<div class="c" style="padding:12px 16px"><strong>DISC/DISG</strong> <span style="color:var(--tx2)">— Dominanz, Initiative, Stetigkeit, Gewissenhaftigkeit.</span></div>
<div class="c" style="padding:12px 16px"><strong>Robinsonliste</strong> <span style="color:var(--tx2)">— Sperrliste: kein Telemarketing an diese Privatpersonen.</span></div>
</div></div>

`;

const SALES_CARDS = [
['Was bedeutet Sales im Gastgewerbe?','Aufbau langfristiger Beziehungen zwischen Kundschaft und Dienstleistungsunternehmen — nicht bloss Zimmer verkaufen. Einkaufsprozesse der Kundenseite verstehen.'],
['Welchen 2 Ps des Marketing-Mix wird Sales zugeordnet?','Place (Vertrieb/Distribution) und Promotion (Kommunikation). Place: Kundschaft zum Buchen bringen. Promotion: persönlicher Verkauf und Event-Marketing.'],
['Was ist der Unterschied zwischen direktem und indirektem Vertrieb?','Direkt = ohne Zwischenhändler. Indirekt = via Reisebüros, OTAs (Booking.com etc.).'],
['Was bedeutet «Farming» im Verkauf?','Reaktiver Verkauf — Anfragen bearbeiten, die von aussen kommen (Bankett, Rezeption, Restaurant). Man «erntet».'],
['Was bedeutet «Hunting» im Verkauf?','Proaktiver Verkauf — Aktive Neukundenakquise: Sales-/Account Management, Aussendienst. Man «jagt».'],
['Nenne 3 Vorteile des direkten Vertriebs.','1. Direkte Kommunikation → Loyalität. 2. Unmittelbare Steuerung/Kontrolle. 3. Keine Mittler-Gebühren/Provisionen.'],
['Nach welchen 3 Kriterien wird im Gastgewerbe segmentiert?','1. Buchungsgrösse (Einzel/Gruppe). 2. Aufenthaltszweck (Business/Leisure). 3. Vertragsverhältnis (mit/ohne Vertrag).'],
['Welche 4 Kernfragen muss die Verkaufsperson über den Einkaufsprozess beantworten?','1. Wie (Ablauf/Stufen)? 2. Wann (Fristen)? 3. Womit (Tools)? 4. Wer (Entscheidungsträger)?'],
['Was ist ein RFP?','Request for Proposal — elektronische Ausschreibung für Hotelverträge, z.B. über Lanyon, Nexus.'],
['Was ist eine TMC?','Travel Management Company — spezialisiertes Firmenreisebüro (Amex GBT, BCD Travel, CWT).'],
['Was ist ein Konsortium im Hotelvertrieb?','Weltweit operierendes Reisebüro, das Buchungen für Firmen abwickelt.'],
['Was ist ein Implant?','Reisebüro auf dem Firmengelände, exklusiv für dieses Unternehmen.'],
['Wie sieht die touristische Marktstruktur bei Paketreisen aus?','Gäste → Reisebüro → Veranstalter (Tour Operator) → Incoming Operator → Hotel.'],
['Ab wie vielen Zimmern spricht man von einer Gruppe?','Ca. ab 10 Zimmern (je nach Unternehmen).'],
['Was ist MICE?','Meetings, Incentives, Conventions, Exhibitions — Geschäftsreisegruppen/Tagungsgeschäft.'],
['Beschreibe den Sicherheitstyp.','Sucht Stabilität, Zuverlässigkeit, konstante Qualität. Preis sekundär. Tipp: Zertifikate betonen, persönliche Betreuung.'],
['Beschreibe den Wirtschaftlichkeitstyp.','Preis-Leistung, Best Deal. Geniesst Preisgespräch. Tipp: Hart verhandeln — liebt ebenbürtige Gegenpartei.'],
['Beschreibe den Prestigetyp.','Ansehen gewinnen. Markenbewusstsein, Status. Tipp: Neuheiten zuerst, Events einladen, Titel verwenden.'],
['Beschreibe den Bequemlichkeitstyp.','Alles aus einer Hand, Rundum-Service. Tipp: Arbeit abnehmen, Referenzen bereithalten.'],
['Wie verteilt sich die Wahrnehmung der Kommunikationsarten?','7% Worte/Inhalt, 38% Stimme/Tonfall, 55% Körpersprache.'],
['Nenne die 4 Ebenen des 4-Ohren-Modells.','1. Sachebene (informieren). 2. Selbstoffenbarung (kundgeben). 3. Beziehungsebene (Haltung). 4. Appellebene (veranlassen).'],
['Warum sind die ersten 30 Sekunden bei Neukunden entscheidend?','Erster Eindruck haftet Jahre. Korrektur ist sehr schwierig und aufwendig.'],
['Was sind offene Fragen und wofür eignen sie sich?','W-Fragen (wer, wie, warum). Info gewinnen, Gespräch im Fluss halten. Ideal für Bedarfsanalyse.'],
['Was ist eine Alternativfrage?','Bietet nur Varianten der Zustimmung («KW 50 oder 51?»). Keine Nein-Option. Gut für Abschluss.'],
['Was ist eine Gegenfrage?','Reagiert auf Einwände, gewinnt Zeit. «Preis zu hoch?» → «Im Verhältnis wozu?»'],
['Was ist eine Ja-Strasse?','Aneinandergereihte Ja-Fragen als Abschlusstechnik — eleganteste Form ohne Druckgefühl.'],
['Nenne die 7 Phasen des Verkaufsgesprächs.','1. Vorbereitung → 2. Warm-up → 3. Bedarfsanalyse → 4. Produktpräsentation → 5. Preisnennung → 6. Abschluss → 7. Nachbearbeitung.'],
['Was ist das Trichtermodell in der Bedarfsanalyse?','Mit breiten Fragen beginnen, schrittweise einschränken. Bedürfnisse herausfinden (bewusste + unbewusste).'],
['Was ist die FAB-Technik?','Feature-Advantage-Benefit: Merkmal → Vorteil → individueller Kundennutzen. Immer nur eine Kette.'],
['Nenne ein FAB-Beispiel.','Merkmal: 24h-Rezeption. → Vorteil: Jederzeit anreisen. → Nutzen: Terminlich flexibel, keine Sorgen bei Verspätung.'],
['Was sind sachliche und emotionale Kaufmotivatoren?','Sachlich = «Mehr» (Effizienz, Gewinn, Zeit). Emotional = «Weniger» (Aufwand, Risiko, Stress).'],
['Was ist die Sandwich-Methode?','1–3 Vorteile → PREIS → 1–3 Vorteile. Psychologische Minimierung. Keine Sprechpause nach Preis!'],
['Warum soll man «kostet» vermeiden?','Negative Assoziationen (Telefonkosten, Mietkosten). Reiner Preis wird automatisch als zu teuer empfunden.'],
['Nenne 4 Kaufsignale.','1. Direkter Kaufwunsch. 2. Fragen nach dem «Danach». 3. Beschäftigung mit Details. 4. Zustimmendes Nicken.'],
['Warum darf man Kaufsignale nicht übersehen?','Wer weiter argumentiert statt abzuschliessen, riskiert Rückentwicklung des Kaufwunsches. Neue Zweifel!'],
['Nenne die 5 Schritte der Einwandbehandlung.','1. Verständnis → 2. Nachfragen → 3. FAB zum Einwand → 4. Rückversichern → 5. Erneuter Abschluss.'],
['Was bedeutet NEIN im Verkauf?','«Noch Etwas Input Nötig» — Einwände signalisieren Interesse!'],
['Nenne die 5 Preisverhandlungs-Strategien.','1. Nutzenargumentation (kostet nichts!). 2. Zugaben. 3. Preis+Leistung kürzen. 4. Preissenkung. 5. Kein Abschluss.'],
['Was ist ein Elevator Pitch?','30–60 Sek.: «Für Sie (Zielgruppe) und Ihr (Problem) ist (Produkt) eine (Kategorie) mit (Hauptvorteil).»'],
['Was ist ein Sales-Blitz?','Intensive Kurzverkaufskampagne, max. 5 Min./Besuch, eine Kernaussage, Infobeschaffung.'],
['Was ist ein Fam-Trip?','Familiarisation Trip — kostenlose Studienreise für Reisebüromitarbeitende/Travel Manager.'],
['Nenne die 5 Schritte der Verkaufsplanung.','1. Analyse → 2. Ziele → 3. Strategie → 4. Massnahmen → 5. Budget.'],
['Was besagt die Pareto-Regel im Verkauf?','80% Ergebnisse mit 20% Aufwand. 20% der Kunden = 80% des Umsatzes.'],
['Was ist die ABC-Analyse?','A = Top-Kunden (intensivste Betreuung). B = Mitte (Potenzial für A). C = geringste Bedeutung (standardisiert).'],
['Was sind die 6Ws im Zielraster?','Was (Zielinhalt), Wieviel (Zahl/%), Wem (Segment), Wann (Frist), Wo (Markt), Wer (Verantwortung).'],
['Was umfasst die primäre Verkaufsplanung?','Nach aussen: Ziele nach Produkten/Kunden/Regionen/Zeiträumen + Einsatzplanung → Sales & Marketingplan.'],
['Was umfasst die sekundäre Verkaufsplanung?','Nach innen: Organisation, Personalplanung, Weiterbildung, Entlöhnung, Verkaufsmittel.'],
['Was sind die zwei Arten von Airline-Geschäft?','1. Crew-Aufenthalte (regelmässig, planbar). 2. Layover (ad-hoc bei Störungen).'],
['Nenne 5 wichtige Tradeshows im Hotelverkauf.','IMEX (MICE), IBTM (Corporate), WTM (Tour Operator), ILTM (Luxus), ITB Berlin (global).'],
['Was ist LRA?','Last Room Availability — Garantie, dass das letzte Zimmer zum Firmenpreis verfügbar ist.'],
['Warum ist die Nachbearbeitung so wichtig?','Sie entscheidet über das Folgegeschäft! Ohne Dankesnachricht, pünktliches Angebot und Abteilungsinfo ist alles wertlos.'],
];

// REGISTRIERUNG
window.TIS = window.TIS || {};
window.TIS.courses = window.TIS.courses || {};
window.TIS.courses.sales = {
  config: courseConfig,
  html: courseHTML,
  flashcards: SALES_CARDS,
};

})();
