// ===== FAQ =====
(function() {
window.TIS = window.TIS || {};
window.TIS.pages = window.TIS.pages || {};
window.TIS.pages.faq = `<!-- FAQ -->
<div class="sec" id="faq">
<h1>FAQ &amp; Über das Projekt</h1>
<p class="sub">Häufige Fragen und Hintergründe zu This Is Student</p>

<div style="display:flex;gap:8px;margin:12px 0 4px"><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.add('open'))">Alle aufklappen</button><button style="font-size:11px;padding:4px 10px" onclick="this.parentElement.nextElementSibling.querySelectorAll('.tl-item').forEach(i=>i.classList.remove('open'))">Alle schliessen</button></div>
<div class="tl">

<div class="tl-item open"><div class="tl-num tl-num-b">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Was ist This Is Student?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">This Is Student ist eine <strong>interaktive Lernplattform</strong>, die als persönliches Projekt im Rahmen des BWS-Studiums an der SHL Schweizerische Hotelfachschule Luzern entstanden ist. Die Plattform verwandelt Vorlesungsstoff in visuell aufbereitete, interaktive Lerninhalte — mit Timelines, Mindmaps, Karteikarten, Quiz und klickbaren Gesetzesartikeln.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Für wen ist die Plattform gedacht?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Primär für <strong>Studierende des BWS-Studiengangs an der SHL</strong>.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-a">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Ist das eine offizielle SHL-Plattform?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Nein!</strong> This Is Student ist ein privates Projekt. Es wird nicht von der SHL betrieben, geprüft oder verantwortet. Die Inhalte basieren auf Vorlesungsunterlagen und Gesetzestexten, sind aber eigenständig aufbereitet. Bei Widersprüchen gilt immer der offizielle Vorlesungsstoff bzw. das Gesetz.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich mich auf die Inhalte verlassen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Die Inhalte wurden mit grosser Sorgfalt erstellt und orientieren sich an den aktuellen Gesetzestexten und Vorlesungsunterlagen. Trotzdem: <strong>keine Gewähr</strong> für Richtigkeit und Vollständigkeit. Die Plattform ersetzt weder die Vorlesung noch eine Rechtsberatung. Im Zweifelsfall gilt immer der <strong>Gesetzestext</strong> (via Fedlex) und die <strong>offizielle Vorlesung</strong>. Fehler melden hilft allen — nutze dafür den Support.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-p">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Was kann ich mit der Plattform machen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body" style="line-height:1.9"><strong>Lernen &amp; Verstehen:</strong> Jedes Kapitel erklärt den Stoff visuell mit Timelines, farbigen Cards und Merksätzen. Klicke auf Gesetzesartikel für den Originaltext + einfache Erklärung. Klicke auf Abkürzungen für eine Definition.<br><br><strong>Repetieren:</strong> Karteikarten zum Durchklicken. Du kannst eigene Karten hinzufügen — diese werden geräteübergreifend synchronisiert.<br><br><strong>Testen:</strong> Das Quiz-System generiert Fragen aus den Karteikarten. Der Lernfortschritt merkt sich, was du schon kannst (sicher/wackelig/unsicher) und priorisiert schwierige Fragen.<br><br><strong>Üben:</strong> Interaktive Übungen mit Korrektur-Funktion — z.B. siebenstufige Erfolgsrechnung mit randomisierten Zahlen, GoR-Beurteilungen, MWST-Berechnungen.<br><br><strong>Nachschlagen:</strong> Glossar mit Abkürzungen und Formeln. Zusammenfassungen als Mindmaps.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Was bedeuten die klickbaren Elemente?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-sub">
<div class="c ca"><div class="ct2"><span class="b bb">Art. 319 OR</span> Farbige Badges</div><div class="cd">Klick öffnet ein Popup mit dem Gesetzestext + einfacher Erklärung + Link zu Fedlex.</div></div>
<div class="c cg"><div class="ct2"><span class="abk" style="pointer-events:none">EBITDA</span> Gepunktete Unterstreichung</div><div class="cd">Abkürzung oder Fachbegriff. Klick öffnet ein Popup mit der Erklärung.</div></div>
<div class="c cm"><div class="ct2">Farbige Cards mit Seitenstreifen</div><div class="cd">Wichtige Informationen, farblich gruppiert. Rosa = Schwerpunkt, Rot = Warnung/Wichtig, Grün = Positiv, Orange = Achtung.</div></div>
<div class="c cp"><div class="ct2">Merksätze (violett, kursiv)</div><div class="cd">Eselsbrücken und Prüfungstipps — die solltest du dir besonders merken!</div></div>
</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Welche Fächer gibt es?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body"><strong>Aktuell verfügbar (4):</strong><br>• <strong>Recht 2 (SchKG)</strong> — Schuldbetreibung, Pfändung, Konkurs, Sicherungsmittel<br>• <strong>Arbeitsrecht</strong> — OR, ArG, L-GAV mit 10 Kapiteln inkl. Mutterschutz, Lohnfortzahlung, Arbeitszeit<br>• <strong>Controlling 2</strong> — Kennzahlen, Kostenrechnung, Kalkulation, Investitionsrechnung<br>• <strong>Financial Accounting 3</strong> — Bilanz &amp; ER, MWST, Personal, Abschlüsse, Kennzahlen, Gewinnverwendung</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-a">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kommen neue Fächer dazu?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Ja — aber zwischen Vorlesungen, Prüfungen und dem normalen Wahnsinn des Studentenlebens hat der Tag leider nur 24 Stunden. Dieses Projekt entsteht in der Freizeit, mit viel Kaffee und noch mehr Ehrgeiz. Es gibt darum keinen festen Zeitplan und keine fixen Release-Daten. Neue Kurse erscheinen, sobald sie fertig und geprüft sind. Was bereits in Arbeit ist, siehst du auf der Kurse-Übersicht.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Werden meine Daten gespeichert?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Die Plattform läuft als statische Website auf GitHub Pages. Login-Daten und Dark/Light-Mode werden lokal im Browser gespeichert. Eigene Karteikarten werden über Supabase (Rechenzentrum Zürich) synchronisiert — nur du siehst deine eigenen Karten. Kein Tracking, keine Werbung, keine Cookies von Dritten.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-p">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Ich habe einen Fehler gefunden — was tun?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Danke! Nutze den Support-Button unten auf der Seite oder melde dich direkt. Fehler werden so schnell wie möglich korrigiert.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Funktioniert die Plattform auf dem Handy?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Ja, die Plattform ist responsive und funktioniert auf Desktop, Tablet und Mobile. Für die beste Erfahrung empfehlen wir einen modernen Browser (Chrome, Safari, Firefox).</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich offline lernen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Die Plattform braucht eine Internetverbindung für den Login und die Synchronisation eigener Karteikarten. Die Lerninhalte selbst werden beim Laden der Seite vollständig geladen.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-a">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich eigene Karteikarten erstellen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Ja. Auf jeder Karteikarten-Seite gibt es einen «+ Neue Karte»-Button. Deine eigenen Karten werden mit deinem Account synchronisiert und erscheinen auf allen Geräten. Du kannst sie auch wieder löschen.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Wie funktioniert das Quiz?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Das Quiz generiert Multiple-Choice-Fragen automatisch aus den Karteikarten. Das System merkt sich deinen Fortschritt: Fragen, die du falsch beantwortest, kommen häufiger dran. Fragen, die du sicher kannst, erscheinen seltener. So lernst du gezielt deine Schwächen.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-p">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Was ist der Unterschied zwischen Karteikarten und Quiz?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Karteikarten sind zum freien Repetieren — du klickst durch und überprüfst dich selbst. Das Quiz testet dich aktiv mit Multiple-Choice und trackt deinen Lernfortschritt (sicher / wackelig / unsicher / noch offen).</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich den Dark Mode aktivieren?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Ja. Klicke auf das Sonnen-/Mond-Symbol oben in der Navigation. Es gibt drei Modi: Auto (folgt dem System), Hell und Dunkel.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Warum brauche ich einen Login?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Der Login stellt sicher, dass nur berechtigte Personen Zugang haben und dass deine eigenen Karteikarten deinem Account zugeordnet werden können.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-a">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Ich kann mich nicht einloggen — was tun?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Prüfe Benutzername und Passwort auf Tippfehler (Gross-/Kleinschreibung beachten). Falls es weiterhin nicht klappt, nutze den Support.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich mein Passwort ändern?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Diese Funktion befindet sich aktuell in Testung. Bei Problemen wende dich über den Support.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-p">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich meinen Lernfortschritt zurücksetzen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Ja. Im Quiz gibt es einen «Fortschritt zurücksetzen»-Button. Damit werden alle Fragen wieder auf «noch offen» gesetzt und du startest von vorne.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Werden die Übungen benotet?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Nein. Alle Übungen, Quiz und Karteikarten sind rein zum Üben. Es gibt keine Noten und keine Auswertung die an Dritte geht.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich Inhalte ausdrucken?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Aktuell noch nicht. Eine Druckfunktion ist für die Zukunft angedacht.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-a">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Gibt es eine App?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Geplant — TBA. Aktuell funktioniert die Plattform über den Browser auf allen Geräten.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Wer steckt hinter This Is Student?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Gianluca Mattiello — BWS-Student an der SHL Schweizerische Hotelfachschule Luzern.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-p">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Wie kann ich das Projekt unterstützen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Aktiv mitmachen! Zusammenfassungen zusenden, Tipps geben, Fehler melden, Verbesserungsvorschläge — alles was dir auffällt hilft. Nutze dafür den Support.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-b">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Warum sieht etwas anders aus als in der Vorlesung?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Die Inhalte werden eigenständig aufbereitet und didaktisch neu strukturiert. Es kann deshalb sein, dass Reihenfolge, Formulierungen oder Schwerpunkte von der Vorlesung abweichen. Die fachliche Grundlage bleibt aber dieselbe. Im Zweifel gilt immer das Kompendium und der Dozent.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-g">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Kann ich Fächer oder Features vorschlagen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Klar. Schreib über den Support was du dir wünschst — sei es ein bestimmtes Fach, eine Funktion oder eine Verbesserung. Versprechen kann ich nichts, aber jeder Input wird gelesen.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-a">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Wird die Plattform nach dem Studium weiterleben?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Das ist der Plan. Auch wenn sie als Semesterprojekt gestartet ist, soll This Is Student langfristig wachsen und auch zukünftigen Jahrgängen nützen.</div></div></div>

<div class="tl-item"><div class="tl-num tl-num-r">?</div><div class="tl-head" onclick="this.parentElement.classList.toggle('open')"><div><div class="tl-title">Darf ich die Plattform teilen?</div></div><div class="tl-arrow">&#9654;</div></div><div class="tl-detail"><div class="tl-body">Die Plattform ist für den persönlichen Gebrauch gedacht. Du darfst den Link gerne mit Mitstudierenden teilen. Eine kommerzielle Nutzung oder Weiterverbreitung als eigenes Produkt ist nicht gestattet.</div></div></div>

</div>

<div style="text-align:center;padding:24px 0">
<button onclick="go('home')" style="font-size:13px;padding:10px 24px">← Zurück zur Startseite</button>
<button class="bp1" onclick="go('kurse')" style="font-size:13px;padding:10px 24px;margin-left:10px">Zu den Kursen →</button>
</div>
`;
})();
